### ISSUE TITLE
Player models are invisible in 1.13.2 server

### ISSUE THREAD

**Issue by CNAmira** [ViaVersion/ViaFabric#1]
![ce6rxm4sz 3h l 5sl k95c](https://user-images.githubusercontent.com/4312700/53710743-a4e5cf80-3e79-11e9-8dce-cbdc7eb93b54.jpg)

**Comment by creeper123123321** [comment]
Is it related with this snapshot bug? https://bugs.mojang.com/browse/MC-144098

**Comment by CNAmira** [comment]
I'm not sure, but it seems to be.

发自我的 iPhone

**Comment by creeper123123321** [comment]
Was it fixed by Mojang?

**Comment by CNAmira** [comment]
Recently I moved to another city, the network situation is very bad so I can't connect to Mojang's server and update my game client :(

**Comment by CNAmira** [comment]
Okay, it is fixed by Mojang.
