### ISSUE TITLE
Can't join any 1.9.1 server

### ISSUE THREAD

**Issue by RaphiMC** [ViaVersion/ViaFabric#102]
**Describe the bug, provide any errors**
When trying to join a server using the 1.9.1 protocol ViaFabric throws errors or doesn't work

**Is this happening specifically on ViaFabric?**
Yes, a 1.9.1 client can join when using ViaVersion on a spigot 1.8 server
- [X] It seems to not happen when using ViaVersion/ViaBackwards/ViaRewind installed on Bukkit/BungeeCord/Sponge/Velocity server.

**How can we reproduce it?**
Select 1.9.1 protocol
Join a 1.9.1 server

**Expected behaviour**
Expect to join the 1.9.1 server

**Comment by creeper123123321** [comment]
It may be a viaversion bug

**Comment by RaphiMC** [comment]
Probably yes but if I try joining a spigot 1.8 server (with only VV installed) using a 1.9.1 client it works

**Comment by creeper123123321** [comment]
you need to test viaversion on 1.9.1 server

**Comment by creeper123123321** [comment]
confirmed, i checked source code and it's viaversion bug
