### ISSUE TITLE
[1.16.5] Incorrect block entity translation?

### ISSUE THREAD

**Issue by Miv2nir** [ViaVersion/ViaFabric#116]
**Describe the bug, provide any errors**
On minecraftonline.com server, in tge community server there is a sea lantern riding around and a cake, both are entities. However, when joining with viafabric or viaaas, the lantern turns into red stained glass pane, and the cake appears as a soul torch for some reason. (The cake doesn't appear at all for me with viaaas + geyser)

It happens on both viaFabric and Viaaas

**How can we reproduce it?**
1. Login to minecraftonline.com using viaFabric or viaaas'
2. Go through the rules chamber to the spawn area
3. Enter the community center and observe the bugged entities.

There should be a sea lantern riding around the building and a smaller sized cake as an entity near the entrance. Login with 1.12.2 to see how it's meant to be seen

![2021-04-08_15 39 07](https://user-images.githubusercontent.com/70204046/114113746-11005080-98e8-11eb-9341-d3b6c19cada3.png)
![2021-04-08_14 29 54](https://user-images.githubusercontent.com/70204046/114113767-1b224f00-98e8-11eb-8f97-70a4d098c5c1.png)
![Screenshot_20210409-035003_Minecraft](https://user-images.githubusercontent.com/70204046/114113778-21b0c680-98e8-11eb-869c-df27836c0c90.png)
![Screenshot_20210409-035022_Minecraft](https://user-images.githubusercontent.com/70204046/114113796-2d9c8880-98e8-11eb-8284-711f0f0b7ddf.png)

**ViaVersion Dump:**
https://dump.viaversion.com/095411e3bdcdf81e5fe27f60330f80af08f478aca5475a72b9365c1d2aaaf235

**Comment by creeper123123321** [comment]
ViaVersion issue
