### ISSUE TITLE
Y: -64 is not proper translated and causes glitches.

### ISSUE THREAD

**Issue by Kichura** [ViaVersion/ViaFabric#134]
**Describe the bug, provide any errors**
When entering a 1.17 server that has the Y levels adjusted using a datapack, The mod has no clue what to do with it and instead uses the default 255 - 0 Y instead.

**Is this happening specifically on ViaFabric?**
(Optional)

- [ ] It seems to not happen when using ViaVersion/ViaBackwards/ViaRewind installed on Bukkit/BungeeCord/Sponge/Velocity server.

**How can we reproduce it?**
1. Start any fabric client that has all three ViaFabric, ViaBackwards and ViaRewind (DEV versions) installed.
2. Start any 1.17-related server with mojang's official 1.17 datapack installed.
3. Join the server while protocol is set to 755 via 1.16.5.
4. Attempt to dig straight down to 0 and further, This will cause the player to start getting stuck without any purpose to escape.

**Expected behaviour**
The 384 - -64 Y is translated and allows the player to move below 0 just fine without too many issues.

**Screenshots**
https://i.imgur.com/Jv2u1bb.png

**ViaVersion Dump:**
https://dump.viaversion.com/b2387fb650e570a36fe8d812819eecf6eac87db5dd3ecbe2d1df86aaa020d3bb

**Additional server info**
1: The server does NOT have a proxy present,
2: Fabric with all three mods as mentioned above,
3: The client has client-side mode enabled.

**Comment by KennyTV** [comment]
Won't fix, there should be a clear warning in the console about it.
