### ISSUE TITLE
Crashes on 1.17.1 server startup

### ISSUE THREAD

**Issue by Neubulae** [ViaVersion/ViaFabric#141]
[crash-2021-07-07_21.08.52-server.txt](https://github.com/ViaVersion/ViaFabric/files/6777332/crash-2021-07-07_21.08.52-server.txt)
[mods.txt](https://github.com/ViaVersion/ViaFabric/files/6777335/mods.txt)

**Comment by creeper123123321** [comment]
https://github.com/ViaVersion/ViaFabric/commit/c35f2ff9702807d547612db6413eaaf29a294e26
