### ISSUE TITLE
1.18 compatibility

### ISSUE THREAD

**Issue by Username404-59** [ViaVersion/ViaFabric#146]
**Describe the bug, provide any errors**
[error.txt](https://github.com/ViaVersion/ViaFabric/files/6842135/error.txt)

**Is this happening specifically on ViaFabric?**
- It seems to not happen when using ViaVersion/ViaBackwards/ViaRewind
 on other platforms

**How can we reproduce it?**
- Run ViaFabric on a 1.18 server with the following compiled builds of ViaVersion and ViaBackwards
https://www.mediafire.com/file/ayeowwmaolg6snk/ViaVersion-4.0.2-1.18-experimental1-SNAPSHOT.jar/file
https://www.mediafire.com/file/zqj5kapw08nv6lh/ViaBackwards-4.0.2-1.18-experimental1-SNAPSHOT.jar/file
Edit: - Set the minecraft version required by viafabric to "*" (or "1.18.x"?)

**Comment by creeper123123321** [comment]
I tried and this happens:
```
[20:44:10] [main/FATAL]: A critical error occurred
net.fabricmc.loader.discovery.ModResolutionException: Could not find required mod: viafabric requires {minecraft @ [1.8.x || 1.14.x || 1.15.x || 1.16.x || 1.17.x]}
```

**Comment by Username404-59** [comment]
Oh well, I forgot to mention that I set viafabric's required minecraft version to "*", viafabric wasn't meant to support 1.18 anyway 😅
