### ISSUE TITLE
[1.12] Memory leak

### ISSUE THREAD

**Issue by Tomatobird8** [ViaVersion/ViaFabric#150]
Memory usage accumulates and framerate decreases as the world is traveled. This seems to be an issue with ChunkNibbleArrays not being cleared and lighting being processed in all of those chunks.

This issue occurs on ViaFabric client connected to a vanilla 1.12.2 server as well as on a fabric client without ViaFabric, connected to a 1.12.2 PaperMC server with ViaVersion. Possibly other setups as well but these are what I've tested.

To reproduce, using a 1.17.1 client join a 1.12.2 server and explore the world for a while. May take more than 100k blocks

Heap dump memory leak suspect report using Memory Analyzer:
![01](https://i.imgur.com/X2aesN2.jpg)
![02](https://i.imgur.com/OO1DWs5.jpg)

**Comment by creeper123123321** [comment]
Does installing Sodium fixes it?

**Comment by Tomatobird8** [comment]
> Does installing Sodium fixes it?

No. Memory leak/FPS Drops happen with and without sodium.

**Comment by Kichura** [comment]
Confirmed on windows server 2019 machine without any mods other than viafabric + the api installed.

**Comment by Kichura** [comment]
Decided to try and recreate this problem on my new-current linux machine and this time it seems to vary. *(Sometimes it works fine and sometimes it seems to slip up)*
