### ISSUE TITLE
Port to Legacy Fabric?

### ISSUE THREAD

**Issue by creeper123123321** [ViaVersion/ViaFabric#16]
https://github.com/Legacy-Fabric

**Comment by creeper123123321** [comment]
CottonMC/ClientCommands#13

**Comment by creeper123123321** [comment]
Legacy-Fabric/fabric#9 Legacy Fabric may provide client-side command api

**Comment by hYdos** [comment]
the command api is now finished. once i add it to bintray you should be able to use it

**Comment by creeper123123321** [comment]
ViaFabric won't support client-side command on 1.8 as it doesn't receive OP level
