### ISSUE TITLE
Could not execute entrypoint stage 'main' due to errors, provided by 'viafabric-mc117'!

### ISSUE THREAD

**Issue by enzomtpYT** [ViaVersion/ViaFabric#162]
**Describe the bug, provide any errors**
- A clear and concise description of what the bug is.
https://paste.ee/p/bZTcr

**Is this happening specifically on ViaFabric?**
(Optional)
Only on viafabric version > 0.4.3 build 230 ( build 230 works but higher builds don't work )

**How can we reproduce it?**
- Steps to reproduce the behavior
- Start the game with via fabric >0.4.3+230
- Game crashes

**Expected behaviour**
- A clear and concise description of what you expected to happen.
- Just the game will start

**Screenshots**
- If applicable, add screenshots to help explain your problem.
- No screens

**ViaVersion Dump**
- Type /viaversion dump, and put the link here.
- can't do that

**Additional server info**
- Is server using a proxy (eg. BungeeCord/Velocity)?
- 1.17.1 Fabric client

**Comment by creeper123123321** [comment]
Update ViaBackwards
