### ISSUE TITLE
1.18 advancements are not translated.

### ISSUE THREAD

**Issue by Kichura** [ViaVersion/ViaFabric#163]
**Describe the bug, provide any errors**
- When viewing or gaining any advancements on a 1.18 server while using 1.17/1.17.1 as client, the names including descriptions for them are not translated and instead use the code strings instead.

**Is this happening specifically on ViaFabric?**
(Optional)
- [ ] It seems to not happen when using ViaVersion/ViaBackwards/ViaRewind on other platforms.

**How can we reproduce it?**
- 1. Have a 1.17/1.17.1 client with both viafabric and viabackwards installed,
- 2. Join a 1.18 server,
- 3. View the advancements page,
- 4. The 1.18 advancements should be displayed in a non-friendly language.

**Expected behaviour**
- All advancements are properly translated and have their details displayed correctly.

**Screenshots**
![mc](https://user-images.githubusercontent.com/68134602/144689893-57dc6b0e-c729-420d-ab79-d7cfad0ded73.png)

**ViaVersion Dump**
- https://dump.viaversion.com/2ea15620a73ca91d71a39d36a5b0e6ac81341b10a0c5315f7faa216ded33b7ff

**Additional server info**
- The 1.18 server does NOT use a proxy,
- The 1.18 server runs on pure vanilla while the client is on fabric 1.17.1,
- The client has client-side mode enabled.

**Comment by creeper123123321** [comment]
this should be on ViaBackwards

**Comment by Kichura** [comment]
> this should be on ViaBackwards

I was thinking about this twice and then thought i should post this here instead cuz viabackwards was absent from server itself.
