### ISSUE TITLE
Moss Block mapping 1.18 -> 1.17 (may be the problem is caused by ViaBackwards)

### ISSUE THREAD

**Issue by shadichy** [ViaVersion/ViaFabric#171]
**Describe the bug, provide any errors**
- Yes, moss block problem
 Can you use a paste service like https://gist.github.com?
 If possible, install Not Enough Crashes mod to make errors more legible.

**Is this happening specifically on ViaFabric?**
(Optional) 
- haven't tested on spigot

**How can we reproduce it?**
- fabric server 1.12.12, version 1.18.1, installed ViaVersion and ViaBackwards
- vanilla client 1.17.1

**Expected behavior**
- moss block

**Screenshots**
- ![moss](https://imgur.com/XzcTHzd.jpg)

**ViaVersion Dump**
- https://dump.viaversion.com/45feb292327c36404709c62941b92b2dc2c876ec10135b4e55634dcf898ff68b

**Additional server info**
- Is server using a proxy (eg. BungeeCord/Velocity)? No
 What software is it using and what plugins? (Debug HUD may have it (F3)) 
 Are you running on client-side mode? No

**Comment by creeper123123321** [comment]
Was the world upgraded from an older to a newer minecraft version??

**Comment by shadichy** [comment]
> Was the world upgraded from an older to a newer minecraft version??

of course no
