### ISSUE TITLE
ViaFabric (Build 266) crashes on 1.18.1.

### ISSUE THREAD

**Issue by Kichura** [ViaVersion/ViaFabric#175]
**Describe the bug, provide any errors**
When attempting to load ViaFabric (Build 266) from CF or GitHub actions on 1.18.1, It will cause both client & server to crash with mixin errors.

**Is this happening specifically on ViaFabric?**
(Optional)
- [X] It seems to not happen when using ViaVersion/ViaBackwards/ViaRewind on other platforms.

**How can we reproduce it?**
1. Obtain a copy of ViaFabric (Build 266) either from CF or GitHub Actions,
2. Install it to a clean fabric client (1.18.1) along with latest API,
3. Try to start the client,
4. Expect a crash from there.

**Expected behaviour**
- ViaFabric will continue to run properly like in 1.18.2.

**Screenshots**
(Unavailable to provide any screenshots but crash log is available below)

https://pastebin.com/raw/etnDGswG

**ViaVersion Dump**
(Unavailable to share viaversion dump as i am unable to provide any due to the build crashing)

**Additional server info**

1. I am not using any proxy software, (besides, how would you run bungee/velocity on clients?)

2. Client software:
- Loader 0.13.3,
- API 0.46.4+1.18,
- ViaFabric (0.4.6+266-main),
- ViaBackwards 4.2.0.

3. I am using client-side mode for viafabric.

**Comment by SulpherStaer** [comment]
This crash occurs again with Fabric API 0.48.0

**Comment by Kichura** [comment]
Obvious since it says "1.18.2" in the file name, meaning it won't accept older minor versions of 1.18.x.

**Comment by maciejkamo20** [comment]
i get the same error on the latest fabric api, and viafabric for 1.18.2 also latest version, the minecraft launcher says its caused by viafabric, quit code -1, nothing else
