### ISSUE TITLE
kicked when changing dimension on velocity

### ISSUE THREAD

**Issue by Pybr** [ViaVersion/ViaFabric#182]
every time I die in a pvplegacy it kicks me and that's annoying, especially for a PVP server
![SharedScreenshot](https://user-images.githubusercontent.com/107134533/172664703-76814498-26cd-4b77-91aa-7d153ac32de2.jpg)
r

**Comment by FernandoPelarich** [comment]
Same, just that it kicks me when trying to teleport to other world

**Comment by Wudji** [comment]
same

**Comment by creeper123123321** [comment]
please add game log

**Comment by creeper123123321** [comment]
workaround provided on ViaVersion.
download it at https://ci.viaversion.com
