### ISSUE TITLE
Connection Lost when trading with villagers (via 1.19 on a 1.18.2 server)

### ISSUE THREAD

**Issue by Desmonid** [ViaVersion/ViaFabric#184]
**Describe the bug, provide any errors**
when attempting to trade with my established villagers I get disconnected out (see screenshots) 
note that this seems to not happen with fresh villagers with no xp who just selected their job site, only to existing villagers with a name or some xp from being traded with previously

**Is this happening specifically on ViaFabric?**
(Optional)
yes, uninstalling viafabric and connecting directly with older version solved the bug

**How can we reproduce it?**
using viafabric 1.19 connect to a 1.18.2 server and attempt to trade with an established villager.

**Expected behaviour**
normal trade window opens and no dc expected

**Screenshots**
https://cdn.discordapp.com/attachments/882419210582646785/984732253475184690/unknown.png
https://cdn.discordapp.com/attachments/882419210582646785/984732343841488936/unknown.png

**ViaVersion Dump**
https://dump.viaversion.com/2fb6acf2b5aa94f59da9876234118635babc295404a4fd4f4fba61076414fd1a

**Additional server info**
- Is server using a proxy (eg. BungeeCord/Velocity)?
fabric carpet minecraft server on 1.18.2

**Comment by kennytv** [comment]
Your used/bundled ViaVersion is outdated

**Comment by Desmonid** [comment]
This still applies with the latest build on curseforge.
