### ISSUE TITLE
Sending a chat message kicks all player from server, when Styled Chat is installed [1.18.2 -> 1.19]

### ISSUE THREAD

**Issue by Soham52** [ViaVersion/ViaFabric#185]
**Describe the bug, provide any errors**
- The server kicks all player from versions lower than 1.19 when they send a chat message
- Server Log : https://pastebin.com/1e3eUAke

**How can we reproduce it?**
- Create a 1.19 server
- Install Styled Chat by Patbox
- Install ViaRewind
- join through 1.18.2
- send a chat message

**Expected behaviour**
- Chat message pops up in the chat and is seen by all

**Screenshots**
- ![image](https://user-images.githubusercontent.com/73898737/175488139-93198c9c-6b22-4f95-bc31-d34ac640182c.png)

**ViaVersion Dump**
- https://pastebin.com/RU6WYiTB

**Additional server info**
- Is server using a proxy : no
 What software is it using and what plugins? : Fabric, Styled chat
 Are you running on client-side mode? : no

**Comment by svr333** [comment]
Can confirm, also happens on 1.17.1

**Comment by Soham52** [comment]
> was fixed by [ViaVersion/ViaBackwards#455](https://github.com/ViaVersion/ViaBackwards/pull/455)

Not fixed
Still persists, as that commit implements the chat type and does not fix the incompatibility with Styled Chat

**Comment by Gerrygames** [comment]
Please test again with the newest master build and send the new error message.
The old error message does not make any sense with this version.
Newest master build:
https://ci.viaversion.com/view/ViaBackwards/job/ViaBackwards/

**Comment by Soham52** [comment]
> Please test again with the newest master build and send the new error message. The old error message does not make any sense with this version. Newest master build: https://ci.viaversion.com/view/ViaBackwards/job/ViaBackwards/

Umm so this is interesting... Using this version the player is not kicked and the message is sent but it can't be seen by anyone, and this error is sent in the console `[18:04:45] [Netty Server IO #1/WARN]: Missing chat type translation for key %s`
also the same error persists when typing /viaversion dump in the console

**Comment by Soham52** [comment]
> > Please test again with the newest master build and send the new error message. The old error message does not make any sense with this version. Newest master build: https://ci.viaversion.com/view/ViaBackwards/job/ViaBackwards/
> 
> Umm so this is interesting... Using this version the player is not kicked and the message is sent but it can't be seen by anyone, and this error is sent in the console `[18:04:45] [Netty Server IO #1/WARN]: Missing chat type translation for key %s` 
Also the same error persists when typing /viaversion dump in the console

**Comment by Gerrygames** [comment]
Okay this is fixed with https://github.com/ViaVersion/ViaBackwards/commit/282afe94cc220fc8431609935998e57cc72b11e4.
However the dev version dropped support for 1.19.0 and only supports 1.19.1. So you will have to wait for that to be released.
