### ISSUE TITLE
Sending too many packets!

### ISSUE THREAD

**Issue by infikot** [ViaVersion/ViaFabric#186]
Strange things happen when accessing any server with ViaFabric. Sometimes it **kicks** me, sometimes it just warns me that my client is **sending too many packets**, although I didn't even do anything.

![image](https://user-images.githubusercontent.com/92332233/176717789-7db35a26-f74e-4e89-920c-b1785575078b.png)

**Comment by creeper123123321** [comment]
https://viaversion.atlassian.net/wiki/spaces/VIAVERSION/pages/54100070/Configuration
see "Global Packet Limiter Options"
