### ISSUE TITLE
Writing in a book and quill kicks player on a server [1.18.2 -> 1.19]

### ISSUE THREAD

**Issue by Soham52** [ViaVersion/ViaFabric#187]
**Describe the bug, provide any errors**
- Writing in a book and quill kicks the player
- Server log : https://pastebin.com/K1z3zZbw

**How can we reproduce it?**
- Create a fabric sever on 1.19
- install viafabric and viabackward
- join through 1.19
- get a book and quill and write something in it

**Expected behaviour**
- after pressing done, the book is signed and the player is not kicked

**Screenshots**
- ![image](https://user-images.githubusercontent.com/73898737/176834227-e65440b6-a514-45b1-ae40-4a9f619c4790.png)

**ViaVersion Dump**
- https://pastebin.com/88T09mma

**Additional server info**
- Is server using a proxy (eg. BungeeCord/Velocity) ? : No
 What software is it using and what plugins? : Fabric; carpet, disfarbic, etc (can be seen in server log)
 Are you running on client-side mode? : No

**Comment by kennytv** [comment]
Can't help you without a dump, you were probably outdated

**Comment by creeper123123321** [comment]
I'm still able to reproduce on latest VIAaaS

**Comment by creeper123123321** [comment]
> I'm still able to reproduce on latest VIAaaS with a 1.7 client
> 
> ```
> Internal Exception: io.netty.handler.codec.DecoderException: java.io.IOException: Packet 0/13 (class_2820) was larger than I expected, found 206 bytes extra whilst reading packet 13
> ```

looks like viarewind related
