### ISSUE TITLE
Lost connection when attempting to trade with villager (1.19 client, 1.18.2 server)

### ISSUE THREAD

**Issue by corruptmemry** [ViaVersion/ViaFabric#189]
**Describe the bug, provide any errors**
When i'm trying to trade with villager i'm getting kicked from the server.
My client is 1.19 and server is 1.18.2.

**Is this happening specifically on ViaFabric?**
(Optional)
Uninstalling ViaFabric and using 1.18.2 without it solves the bug.

**How can we reproduce it?**
Using 1.19 with ViaFabric connect to 1.18.2 server and attempt to trade with a villager.

**Expected behaviour**
Trade window opens normally.

**Screenshots**
https://0x0.st/oQQN.png
https://0x0.st/oQQZ.mp4

**ViaVersion Dump**
https://dump.viaversion.com/6481238d9a93a9f3edd20044fb28bcf6d0df02163401a1304e17a2901effe665

**Additional server info**
Waterfall proxy, Purpur server.

**Comment by Kichura** [comment]
Your viafabric is outdated, Please update it to 0.4.7+7 from modrinth.
