### ISSUE TITLE
Idea: ViaModded add-on

### ISSUE THREAD

**Issue by creeper123123321** [ViaVersion/ViaFabric#19]
This theoretical add-on could allow Fabric modded servers without installing the mod in client possible, and could allow joining with different Fabric server and client versions

**Comment by Username404-59** [comment]
That would be awesome!

**Comment by creeper123123321** [comment]
This mod allows connecting to fabric servers with vanilla https://github.com/TheEpicBlock/PolyMc

**Comment by Username404-59** [comment]
But will ViaFabric still works with vanilla servers when using PolyMc?

**Comment by creeper123123321** [comment]
very cursed
