### ISSUE TITLE
Bug on 1.11.2-1.9 on funcraft.net

### ISSUE THREAD

**Issue by Finoway** [ViaVersion/ViaFabric#192]
**Describe the bug, provide any errors**
- I went to do a hikabrain on the server funcraft.net but while doing the game I died and I ended up with an error that will be written below and I couldn't move at all and I was kicked out of the game for "Flying is not enable on this server" only on 1.19.

 Can you use a paste service like https://gist.github.com?
1.19 :
- https://gist.github.com/Finoway/fdf68c1122db0a958e94e6f8c7e2de08 on 1.19 fabric with only [Fabric API](https://fabricmc.net/) v0.58.0+1.19, [Mod Menu](https://minecraft.curseforge.com/projects/modmenu) v4.0.4 and [ViaFabric](https://viaversion.com/fabric) 0.4.7+11-main
- https://gist.github.com/Finoway/7b069c788502a9902d9f4d8e8d04a3da  on 1.19 fabric with only [Fabric API](https://fabricmc.net/) v0.58.0+1.19, [Not Enough Crashes](https://www.curseforge.com/minecraft/mc-mods/not-enough-crashes) v1.4.6+1.19 and [ViaFabric](https://viaversion.com/fabric) 0.4.7+11-main
1.18.2:
- https://gist.github.com/Finoway/2569945b0ebf433241bc8640449c0b79 on 1.18.2 fabric with only [Fabric API](https://fabricmc.net/) v0.58.0+1.18.2, [Mod Menu](https://minecraft.curseforge.com/projects/modmenu) v3.2.3 and [ViaFabric](https://viaversion.com/fabric) 0.4.7+11-main

**How can we reproduce it?**
- Use minecraft 1.19 with fabric, viafabric, fabric api. Join any game on funcraft.net and die once I can't move at all 

**Expected behaviour**
- A clear and concise description of what you expected to happen.

**Screenshots**
Once dead and I can't move my vision is shaken and when I try to open my inventory it closes directly with my red character
![2022-07-26_01 13 54](https://user-images.githubusercontent.com/48923336/180890291-d642ce2e-1c0c-4c89-9d73-a2a3802c703d.png)

**ViaVersion Dump**
- I can't

**Additional server info**
- Is server using a proxy (eg. BungeeCord/Velocity)?
The server use "BungeeCord-FunCraft (git:BungeeCord-Bootstrap:1.11-fun-SNAPSHOT:09496f5:113) <- Spigot"
- What software is it using and what plugins?
Spigot
- Are you running on client-side mode?
Yes

**Comment by Calvineries** [comment]
The issue is still current.

Here are the errors that show up in the console when you die:

[1](https://media.discordapp.net/attachments/706932420615864332/1101524045066928238/image.png?width=1439&height=321)

**Comment by Finoway** [comment]
Hello,

We won't be able to test the bug anymore as the FunCraft minecraft server closes on Saturday August 26 at 10:00 pm (Europe/Paris).
