### ISSUE TITLE
Viafabric Incompatibility Bug

### ISSUE THREAD

**Issue by 15801915131** [ViaVersion/ViaFabric#197]
### `/viaversion dump` Output

I don't do so :(

### Console Error

java.util.ConcurrentModificationException
        at java.base/java.util.ArrayList$Itr.checkForComodification(ArrayList.java:1013)
	at java.base/java.util.ArrayList$Itr.next(ArrayList.java:967)
	at com.google.common.collect.AbstractMapBasedMultimap$WrappedCollection$WrappedIterator.next(AbstractMapBasedMultimap.java:473)
	at java.base/java.util.AbstractCollection.toArray(AbstractCollection.java:146)
	at java.base/java.util.ArrayList.addAll(ArrayList.java:670)
	at com.google.common.collect.AbstractMapBasedMultimap$WrappedCollection.addAll(AbstractMapBasedMultimap.java:516)
	at com.google.common.collect.AbstractMultimap.putAll(AbstractMultimap.java:88)
	at com.google.common.collect.ArrayListMultimap.putAll(ArrayListMultimap.java:62)
	at fi.dy.masa.minihud.util.DataStorage.getCopyOfStructureData(DataStorage.java:509)
	at fi.dy.masa.minihud.renderer.OverlayRendererStructures.getStructuresToRender(OverlayRendererStructures.java:109)
	at fi.dy.masa.minihud.renderer.OverlayRendererStructures.update(OverlayRendererStructures.java:62)
	at fi.dy.masa.minihud.renderer.RenderContainer.update(RenderContainer.java:89)
	at fi.dy.masa.minihud.renderer.RenderContainer.render(RenderContainer.java:70)
	at fi.dy.masa.minihud.renderer.OverlayRenderer.renderOverlays(OverlayRenderer.java:50)
	at fi.dy.masa.minihud.event.RenderHandler.onRenderWorldLast(RenderHandler.java:178)
	at fi.dy.masa.malilib.event.RenderEventHandler.onRenderWorldLast(RenderEventHandler.java:111)
	at net.minecraft.class_761.handler$cli000$onRenderWorldLastNormal(class_761.java:6403)
	at net.minecraft.class_761.method_22710(class_761.java:1548)
	at net.minecraft.class_757.method_3188(class_757.java:1031)

### Bug Description

I use viafabric 1.18.1 to join a fabric-carpet server which is 1.16.5.
It seems that minihud throw an unexpected error.
But when I join a 1.18.1 server without viafabric, no unexpected error would happend.
I guess viafabric fogot to translate something.
Here is my mod list:
                appleskin: AppleSkin 2.3.0+mc1.18.1
		autofish: Autofish 0.9.4
		bedrockminer: Bedrock Miner 1.0.0
		carpet: Carpet Mod 1.4.57
		carpet-extra: Carpet Extra 1.4.56
		carpet-tis-addition: Carpet TIS Addition 1.30.0
		clientcommands: Client Commands 2.6
		clientcommands-scripting: Clientcommands Scripting 1.3
		cloth-basic-math: cloth-basic-math 0.6.0
		cloth-config: Cloth Config v6 6.2.57
		com_github_luben_zstd-jni: zstd-jni 1.5.2-2
		com_moandjiezana_toml_toml4j: toml4j 0.7.2
		com_neovisionaries_nv-websocket-client: nv-websocket-client 2.10
		conditional-mixin: conditional mixin 0.2.0
		cullleaves: Cull Leaves 2.3.2
		dashloader: DashLoader 3.1.1+1.18
		dev_quantumfusion_dashloader_dashloader-core: dashloader-core 1.4.0
		dev_quantumfusion_hyphen: hyphen 0.2.0
		double_hotbar: Double Hotbar 1.1.0
		dynamicfps: Dynamic FPS 2.1.0
		ecs: Elytra/Chestplate Swapper 1.2.0-MC1.18
		enhancedblockentities: Enhanced Block Entities 0.5+1.18
		fabric: Fabric API 0.46.6+1.18
		fabric-api-base: Fabric API Base 0.4.2+d7c144a865
		fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.5.3+d7c144a865
		fabric-biome-api-v1: Fabric Biome API (v1) 6.0.2+d7c144a865
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.10+3ac43d9565
		fabric-command-api-v1: Fabric Command API (v1) 1.1.7+d7c144a865
		fabric-commands-v0: Fabric Commands (v0) 0.2.6+b4f4f6cd65
		fabric-containers-v0: Fabric Containers (v0) 0.1.19+d7c144a865
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.4.9+d7c144a865
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.9+3ac43d9565
		fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.10+a1d9bbf565
		fabric-entity-events-v1: Fabric Entity Events (v1) 1.4.6+d7c144a865
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.17+d7c144a865
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.9+d7c144a865
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.11+d7c144a865
		fabric-item-api-v1: Fabric Item API (v1) 1.3.1+691a79b565
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.3.7+3ac43d9565
		fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.9+d7c144a865
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.7+b4f4f6cd65
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.4.13+713c266865
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.9+d7c144a865
		fabric-mining-level-api-v1: Fabric Mining Level API (v1) 1.0.7+d7c144a865
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.12+b4f4f6cd65
		fabric-models-v0: Fabric Models (v0) 0.3.4+d7c144a865
		fabric-networking-api-v1: Fabric Networking API (v1) 1.0.19+d7c144a865
		fabric-networking-v0: Fabric Networking (v0) 0.3.6+b4f4f6cd65
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.11.5+737332ce65
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.13+d7c144a865
		fabric-particles-v1: Fabric Particles (v1) 0.2.10+526dc1ac65
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.9.2+ad01bfbd65
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.4.11+b0b66fc365
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.4.15+6825030165
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.10+b4f4f6cd65
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.5+d7c144a865
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.19+3ac43d9565
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.12+b4f4f6cd65
		fabric-rendering-v1: Fabric Rendering (v1) 1.10.6+713c266865
		fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 1.0.2+d7c144a865
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.4.15+8906aafd65
		fabric-screen-api-v1: Fabric Screen API (v1) 1.0.8+d7c144a865
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.12+d7c144a865
		fabric-structure-api-v1: Fabric Structure API (v1) 2.1.3+d7c144a865
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.2.9+d7c144a865
		fabric-textures-v0: Fabric Textures (v0) 1.0.10+3ac43d9565
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.3.9+fb3b57b465
		fabric-transfer-api-v1: Fabric Transfer API (v1) 1.5.10+c329913d65
		fabricloader: Fabric Loader 0.14.9
		indium: Indium 1.0.2-alpha3+mc1.18.1
		inventoryprofilesnext: Inventory Profiles Next 1.3.4
		inventorytabs: Inventory Tabs 0.4.2-1.18.1
		io_noties_prism4j: prism4j 2.0.0
		itemscroller: Item Scroller 0.16.0
		java: Java HotSpot(TM) 64-Bit Server VM 18
		jsmacros: Js Macros 1.6.4
		lazydfu: LazyDFU 0.1.2
		litematica: Litematica 0.10.0
		litematica_printer: Litematica Printer 2.1
		magiclib: MagicLib 0.1.14
		malilib: MaLiLib 0.11.8
		masa_gadget_mod: Masa Gadget 2.0.8
		midnightlib: MidnightLib 0.2.9
		minecraft: Minecraft 1.18.1
		minihud: MiniHUD 0.21.3
		modmenu: Mod Menu 3.0.1
		multiconnect-api: MultiConnect API 1.5.10
		notenoughcrashes: Not Enough Crashes 4.1.4+1.18.1
		org_graalvm_js_js: js 21.3.0
		org_graalvm_regex_regex: regex 21.3.0
		org_graalvm_sdk_graal-sdk: graal-sdk 21.3.0
		org_graalvm_truffle_truffle-api: truffle-api 21.3.0
		org_javassist_javassist: javassist 3.28.0-GA
		org_joml_joml: joml 1.10.2
		org_yaml_snakeyaml: snakeyaml 1.30
		pca: Plusls carpet addition mod 0.2.4
		replaymod: Replay Mod 1.18.1-2.6.3
		shulker-dupe: Shulker Dupe 1.0.0
		smoothboot: Smooth Boot 1.18-1.7.0
		sodium: Sodium 0.4.0-alpha6+replaymod.rev.b90e7f3
		tweakermore: TweakerMore 2.10.1
		tweakeroo: Tweakeroo 0.12.3
		tweakmyclient: TweakMyClient 1.2.1+6185c48
		viafabric: ViaFabric 0.4.5+263-main
		viafabric-mc118: ViaFabric for 1.18 0.4.5+263-main
		viaversion: ViaVersion 4.1.2-SNAPSHOT
		voxelmap: Voxelmap 1.18.1-1.10.20
		worldedit: WorldEdit 7.2.9+e20e013
Here is my system information.
	Launched Version: 1.18.1-fabric
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: Intel(R) HD Graphics 5500 GL version 3.2.0 - Build 20.19.15.4463, Intel
	Window size: 1366x705
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: id=1280, source=API, type=ERROR, severity=HIGH, message='Error has been generated. GL error GL_INVALID_ENUM in (null): (ID: 173538523) Generic error' x 10
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	Graphics mode: fast
	Resource Packs: vanilla, Fabric Mods, cullleaves/smartleaves (incompatible), file/[1.17]Tweakeroo Malilib汉化资源包.zip (incompatible), file/醉梦巅峰MASA汉化材质20210227.zip (incompatible), file/XeKr+redstone+display1.17-V1.zip (incompatible), file/护眼大补丸1.18新.zip, file/河豚太阳.zip (incompatible), file/[1.18]铜制品显示 pre-1.zip
	Current Language: 简体中文 (中国)
	CPU: 4x Intel(R) Core(TM) i5-5200U CPU @ 2.20GHz
	Client Crashes Since Restart: 5
	Integrated Server Crashes Since Restart: 0
	Suspected Mods: None

### Steps to Reproduce

1. Use 1.18.1 fabric-client with the mods mentioned in Bug Description to login a server 1.16.5.
2. Leave the server.
3. Join the server again.
4. And You client would crash :(

### Expected Behavior

Once you join a server, you client crash :(

### Additional Server Info

Server: fabric-carpet server with BungeeCord.

### Checklist

- [x] I have checked if this is specific to ViaFabric platform, and doesn't happen when running it on other platforms (Paper/Sponge/Velocity/Waterfall).
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Kichura** [comment]
You have outdated viafabric.

**Comment by 15801915131** [comment]
:( I have to use 1.18.1 minecraft fabric client to join some special server.
Maybe provide the latest .jar file in the next release?

**Comment by Kichura** [comment]
[Check this out](https://www.curseforge.com/minecraft/mc-mods/viafabric/files/3945306), this should work fine properly.

**Comment by 15801915131** [comment]
I am using 1.18.1-fabric, not 1.18.2 :(
