### ISSUE TITLE
Locate Command displays raw Text String

### ISSUE THREAD

**Issue by RayBird99** [ViaVersion/ViaFabric#198]
### `/viaversion dump` Output

https://dump.viaversion.com/09e83349892b8427773508e58178a8d4abd0981576014b701c70dd7f469d21c1

### Console Error

```
Put the paste.gg link or text here.
```

### Bug Description

The /locate command doesn't work and says: commands.locate.success

![2022-09-02_18 58 51](https://user-images.githubusercontent.com/104676867/188106991-a682998f-b570-4273-8bd9-ee7035903e58.png)

### Steps to Reproduce

Log in with a 1.19.X Client
Onto a 1.17.X Server
And use /locate

"/locate village"

### Expected Behavior

As what happens when joining with a 1.18.X Client, the command displays as it should while also giving the ability to click it for an instant teleport.

### Additional Server Info

No Plugins or Mods (except viaversion of course)

ViaVersion 4.4.2

### Checklist

- [X] I have checked if this is specific to ViaFabric platform, and doesn't happen when running it on other platforms (Paper/Sponge/Velocity/Waterfall).
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [x] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by creeper123123321** [comment]
Why is the dump from Paper platform?

**Comment by RayBird99** [comment]
I meant to make the bug report as the viaversion server plugin

**Comment by HowardZHY** [comment]
https://github.com/ViaVersion/ViaBackwards/issues/468
