### ISSUE TITLE
Sign Bug

### ISSUE THREAD

**Issue by 0Ariel0** [ViaVersion/ViaFabric#209]
### `/viaversion dump` Output

https://dump.viaversion.com/e51d88d68ae8cc90862f5b8c423e016a45ffaabf3d2be539ac3ed826d71290cf

### Console Error

Nothing

### Bug Description

I was on a server with my friends and when I was going to put a sign on the door of my house the "GUI" to write didn't appear.

how this bug happens: in single player it works but not on servers, try to enter any server and put a plate on the ground, if it works congratulations that server works, but if nothing appears and the plate is blank, this is my mistake.

I already removed all my mods and just left the fabric api but it still didn't work. I tried to change from "AUTO" to the updated version of my server which was "1.16.4/5" and it still didn't work. I tried to re-install my minecraft and it didn't work. On other servers I tested and there are some that go and I don't even notice it but there are others that don't and they are usually version 1.16-1.16.5 so I don't know what happens just fix it please. I don't have a video or photo because I don't know how to record but in short: I just put a sign and nothing appears, nor the "GUI" that appears to write just leaves it blank and writes but I have to quickly press some key and it's just one é like an "Auto Leave" of the sign

### Steps to Reproduce

1. Enter in a server
2. Take a sign and place
3. if the gui appears, on this server it works.
4. if not, this is my problem

### Expected Behavior

I hoped that the "GUI" would appear and I could write normally.

### Additional Server Info

Does the server use a proxy?
Yes, is Bukkit
What software are used and what plugins/mods?
TLauncher. Nothing, mods there are several, but I removed them all and just left the via fabric and it continued not working.
Are you using client-side mode?
Yes, is just a client mod.
Via Fabric Version?
0.4.9+ 19-main

### Checklist

- [X] I have checked if this is specific to ViaFabric platform, and doesn't happen when running it on other platforms (Paper/Sponge/Velocity/Waterfall).
- [x] I have included a ViaVersion dump.
- [ ] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by creeper123123321** [comment]
https://github.com/ViaVersion/ViaVersion/issues/3027
