### ISSUE TITLE
viafabric 1.15 cant connect to a 1.8 lilypad server

### ISSUE THREAD

**Issue by IdanHo** [ViaVersion/ViaFabric#21]
**Describe the bug, provide any errors**
https://hastebin.com/wuxefuzuba.nginx
when connecting to play.cosmicpvp.com or Syphlex.net or a couple other servers, the client immediatly disconnects and spews out that error ^
NOTE: this doesnt happen on all servers

**How can we reproduce it?**
Try to connect with viafabric 1.15 to one of the servers listed above (they are 1.8.x)

**Expected behaviour**
the client would connect correctly

**Screenshots**

**ViaVersion Dump:**
https://dump.viaversion.com/595974e48930dc0c079112155d9116931f209756b73049ea8faad8d48f221406

**Additional server info**
not sure

**Comment by RaphiMC** [comment]
Also can't join with ViaFabric 1.14.4 on the 1.8 server (tested with play.cosmicpvp.com)

**Comment by Username404-59** [comment]
It's maybe a serverside problem...

**Comment by IdanHo** [comment]
This doesnt have anything to do with litematica, all the same problems happen with a fresh install of fabric.
