### ISSUE TITLE
ViaFabric doesnt allow my Server to fully stop, it keeps Java alive.

### ISSUE THREAD

**Issue by TheCustomFHD** [ViaVersion/ViaFabric#211]
### `/viaversion dump` Output

https://dump.viaversion.com/9dbb473facc162971de1007f2db171c50dbc9485601878885f1a2945c64478ab

### Console Error

```
Put the paste.gg link or text here.
```

### Bug Description

Server is unable to stop.
More details:
I am using the following Fabric Mods under Fabric 1.19, and without ViaFabric, they work as expected, adding ViaFabric makes my Server unable to stop after logging into it. (it seems to run through the entire shutdown stuff, but then just doesnt terminate.)
![Screenshot_20221112_224133](https://user-images.githubusercontent.com/80068329/201495779-de3f233c-3628-4cff-a2c8-9e6cc0e59080.png)

A showcase of the hanging (expecting a terminal prompt)
![Screenshot_20221112_225523](https://user-images.githubusercontent.com/80068329/201496069-5f73d672-04ba-4239-bba3-73941ad3e267.png)

Unsure if this is the right place to post this, but since removing ViaFabric fixes this, id assume so.

### Steps to Reproduce

Start a Server with the mentioned mods, login into it (Java, and maybe Bedrock?) and it should happen. I am willing to upload a limited Snapshot of my Server if needed for further debugging.

### Expected Behavior

Server should just shut down/stop.

### Additional Server Info

Using the following Fabric Mods:
![Screenshot_20221112_224133](https://user-images.githubusercontent.com/80068329/201495923-fe5166f1-b906-4d23-acdf-74fe0608113c.png)

### Checklist

- [ ] I have checked if this is specific to ViaFabric platform, and doesn't happen when running it on other platforms (Paper/Sponge/Velocity/Waterfall).
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by nossebro** [comment]
The issue could be related to this: https://github.com/GeyserMC/Floodgate-Fabric/issues/59

**Comment by Kichura** [comment]
Does updating to 1.19.4 and using latest geyser + floodgate resolve your problem? if not then this seems to be a floodgate issue for sure.

**Comment by TheCustomFHD** [comment]
> The issue could be related to this: [GeyserMC/Floodgate-Fabric#59](https://github.com/GeyserMC/Floodgate-Fabric/issues/59)

This could totally be that. But it's odd that it hasn't happened before without ViaFabric..
(Also sorry for the long wait, i rarely check GH)

> Does updating to 1.19.4 and using latest geyser + floodgate resolve your problem? if not then this seems to be a floodgate issue for sure.


The original Server doesn't really exist anymore though, so i would need to at some point set up a Server and Test with 1.19.4, although i wanted to stay away from anything higher then 1.19 (ignoring that usually i wouldn't go higher then 1.12.2 if i could decently, or 1.16.5, but Fabric was still small then.)

It could be closed.
