### ISSUE TITLE
Message Encoder?

### ISSUE THREAD

**Issue by JustFoxx** [ViaVersion/ViaFabric#212]
### `/viaversion dump` Output

https://dump.viaversion.com/97e94b82c3a3f12eb02e45fa272082e99abaed8031a80acfd9014d675bb30659

### Console Error

https://gist.github.com/JustFoxx/ca2bcd10277bdd3e2dda109452753557

### Bug Description

i cant join on older versions due to this error

### Steps to Reproduce

Just run 1.19.2 server in dev env with viabackwards

### Expected Behavior

be able to join

### Additional Server Info

just plane fabric

### Checklist

- [X] I have checked if this is specific to ViaFabric platform, and doesn't happen when running it on other platforms (Paper/Sponge/Velocity/Waterfall).
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Kichura** [comment]
Update to 1.19.4 and verify if your issue is still present, if it isn't then a reply can be attached whenever possible.
