### ISSUE TITLE
1.19.3 Client Support for 1.19.2 Servers

### ISSUE THREAD

**Issue by NekomusuMae** [ViaVersion/ViaFabric#214]
**Is your feature request related to a problem? Please describe.**
There is no version of ViaFabric that allows 1.19.3 clients to join a 1.19.2 server. The +22 build skips over 1.19.2.

**Is this related specifically to ViaFabric?**
(Optional)
It seems to not apply for ViaVersion/ViaBackwards/ViaRewind installed on Bukkit/BungeeCord/Sponge/Velocity servers.

**Describe the solution you'd like**
1.19.3 client support on 1.19.2 servers.

**Describe alternatives you've considered**
I've tried modifying the fabric.mod.json file to force it to run on a 1.19.2 server but was met with crashes due to classes differing.

**Which versions is this for?**
1.19.2

**Comment by NekomusuMae** [comment]
Did not know you could just provide your own Spigot ViaVersion jar.

**Comment by DBTDerpbox** [comment]
> Did not know you could just provide your own Spigot ViaVersion jar.

did you ever figure this out? i'm having issues with this, adding the spigot viaversion.jar does not seem to have any effect, the server just seems to ignore it. editing fabric.mod.json in the viafabric jar does work, but i'm creating an installer script for a server so doing that wont be very easy
