### ISSUE TITLE
joining blobcraft.tk doesnt work

### ISSUE THREAD

**Issue by StreakMoos** [ViaVersion/ViaFabric#215]
### `/viaversion dump` Output

https://dump.viaversion.com/84ddabd492a2e9b4a81914caf695d87581ac434cf21c88133c8669c502e16030

### Bug Description

joining blobcraft.tk on 1.8.8 doesnt let me join

### Steps to Reproduce

login with a 1.18.2 client and viaversion client side enabled to 1.8x and get on blobcraft.tk

### Expected Behavior

doesnt let me join

### Checklist

- [ ] I have checked if this is specific to ViaFabric platform, and doesn't happen when running it on other platforms (Paper/Sponge/Velocity/Waterfall).
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Kichura** [comment]
Closing this as the server is unreachable on our end.
