### ISSUE TITLE
[Viafabric 0.4.7+11]1.19.3 client can not connect to the server on 1.19.

### ISSUE THREAD

**Issue by li4tlEShr1Mp** [ViaVersion/ViaFabric#216]
### `/viaversion dump` Output

https://dump.viaversion.com/1e881a5cfcb40c098867134d78ab64762ba0069ebaa8717b8e266445a000d827

### Bug Description

A 1.19.3 client can not connect to the server on 1.19.
Failed to connect to the server
Incompatible client! Please use 1.19

### Steps to Reproduce

1. Login with a 1.19.3 client
2. Connect to a 1.19 server

### Expected Behavior

It should connect successfully?

### Additional Server Info

Server's mods list:
        - cloth-basic-math 0.6.1 via cloth-config
        - cloth-config 8.2.88
        - com_github_shevek_parallelgzip af5f5c297e735f3f2df7aa4eb0e19a5810b8aff6 via textile_backup
        - config2brigadier 1.1.3 via fabrictailor
        - fabric 0.57.0+1.19
        - fabric-api-base 0.4.9+e62f51a3a9 via fabric
        - fabric-api-lookup-api-v1 1.6.7+9ff28f40a9 via fabric
        - fabric-biome-api-v1 9.0.14+b2a4a624a9 via fabric
        - fabric-command-api-v1 1.2.6+f71b366fa9 via fabric
        - fabric-command-api-v2 2.1.2+0d55f585a9 via fabric
        - fabric-commands-v0 0.2.23+df3654b3a9 via fabric
        - fabric-containers-v0 0.1.27+df3654b3a9 via fabric
        - fabric-content-registries-v0 3.2.0+07df213ea9 via fabric
        - fabric-convention-tags-v1 1.0.8+37622d24a9 via fabric
        - fabric-crash-report-info-v1 0.2.3+bd0a0d4aa9 via fabric
        - fabric-data-generation-api-v1 5.1.1+a680b9b4a9 via fabric
        - fabric-dimensions-v1 2.1.28+a6d2f785a9 via fabric
        - fabric-entity-events-v1 1.4.16+9ff28f40a9 via fabric
        - fabric-events-interaction-v0 0.4.26+9ff28f40a9 via fabric
        - fabric-events-lifecycle-v0 0.2.25+df3654b3a9 via fabric
        - fabric-game-rule-api-v1 1.0.19+18990361a9 via fabric
        - fabric-item-api-v1 1.5.4+767db26ea9 via fabric
        - fabric-item-groups-v0 0.3.25+9ff28f40a9 via fabric
        - fabric-lifecycle-events-v1 2.1.0+33fbc738a9 via fabric
        - fabric-loot-api-v2 1.1.0+03a4e568a9 via fabric
        - fabric-loot-tables-v1 1.1.3+9e7660c6a9 via fabric
        - fabric-message-api-v1 1.0.1+513f4a59a9 via fabric
        - fabric-mining-level-api-v1 2.1.10+33fbc738a9 via fabric
        - fabric-networking-api-v1 1.0.27+7fe97409a9 via fabric
        - fabric-networking-v0 0.3.14+df3654b3a9 via fabric
        - fabric-object-builder-api-v1 4.0.7+9ff28f40a9 via fabric
        - fabric-particles-v1 1.0.8+dc39553aa9 via fabric
        - fabric-permissions-api-v0 0.2-SNAPSHOT via geyser-fabric
        - fabric-registry-sync-v0 0.9.17+23c4cfefa9 via fabric
        - fabric-rendering-data-attachment-v1 0.3.12+9ff28f40a9 via fabric
        - fabric-rendering-fluids-v1 3.0.5+9ff28f40a9 via fabric
        - fabric-resource-conditions-api-v1 2.0.9+e62f51a3a9 via fabric
        - fabric-resource-loader-v0 0.5.5+a6d2f785a9 via fabric
        - fabric-screen-handler-api-v1 1.2.6+9ff28f40a9 via fabric
        - fabric-transfer-api-v1 2.0.9+e62f51a3a9 via fabric
        - fabric-transitive-access-wideners-v1 1.1.1+9e7660c6a9 via fabric
        - fabricloader 0.14.11
        - fabrictailor 1.8.4
        - geyser-fabric 2.1.0-SNAPSHOT
        - java 17
        - lithium 0.8.1
        - minecraft 1.19
        - org_apache_commons_commons-compress 1.21 via textile_backup
        - org_tukaani_xz 1.9 via textile_backup
        - org_yaml_snakeyaml 1.30 via viafabric
        - syncmatica 0.3.5
        - textile_backup 2.4.0-1.19
        - viafabric 0.4.7+11-main
        - viafabric-mc119 0.4.7+11-main via viafabric
        - viaversion 4.4.0-1.19.1-rc2-SNAPSHOT via viafabric

### Checklist

- [ ] I have checked if this is specific to ViaFabric platform, and doesn't happen when running it on other platforms (Paper/Sponge/Velocity/Waterfall).
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by li4tlEShr1Mp** [comment]
![File](https://user-images.githubusercontent.com/61986408/208735343-e2233aac-985a-44ea-b16f-ea8a303e62e6.png)

**Comment by Kichura** [comment]
Your viaversion is outdated in viafabric file.

**Comment by li4tlEShr1Mp** [comment]
I see, thank u.
