### ISSUE TITLE
Adding Support for 1.19.3 on 1.19.0 Branch

### ISSUE THREAD

**Issue by FFlurff** [ViaVersion/ViaFabric#217]
**Is your feature request related to a problem? Please describe.**

**Is this related specifically to ViaFabric?**
(Optional)
- [ ] It seems to not apply for ViaVersion/ViaBackwards/ViaRewind installed on Bukkit/BungeeCord/Sponge/Velocity servers.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Which versions is this for?**
Does the feature apply to any specific versions? If so put them here.

**Comment by creeper123123321** [comment]
duplicate of #214
