### ISSUE TITLE
Upload to CurseForge

### ISSUE THREAD

**Issue by Madis0** [ViaVersion/ViaFabric#22]
**Is your feature request related to a problem? Please describe.**
I can see it is still in development, but it would be nice to upload it to CurseForge too, for more awareness that this even exists.

**Describe the solution you'd like**
Upload to CurseForge for every version [(API)](https://authors.curseforge.com/knowledge-base/projects/529-api) or some notable, major, tested versions.

**Describe alternatives you've considered**
Alternatively upload it when you are ready to call it a stable version.

**Which versions is this for?**
Just the latest major versions

**Comment by creeper123123321** [comment]
Done. (https://www.curseforge.com/minecraft/mc-mods/viafabric)
