### ISSUE TITLE
Add support for ViaLegacy

### ISSUE THREAD

**Issue by kristibektashi** [ViaVersion/ViaFabric#221]
**Is your feature request related to a problem? Please describe.**
ViaLegacy is a ViaVersion addon that allows you to connect to Minecraft servers before 1.7
https://github.com/RaphiMC/ViaLegacy

**Is this related specifically to ViaFabric?**
(Optional)
- [ ] It seems to not apply for ViaVersion/ViaBackwards/ViaRewind installed on Bukkit/BungeeCord/Sponge/Velocity servers.

**Describe the solution you'd like**
I want ViaLegacy to be supported on ViaFabric

**Describe alternatives you've considered**

**Which versions is this for?**
Does the feature apply to any specific versions? If so put them here.

**Comment by kristibektashi** [comment]
Related issue: https://github.com/RaphiMC/ViaLegacy/issues/3

**Comment by creeper123123321** [comment]
this should be on vialegacy issue tracker

**Comment by kristibektashi** [comment]
> this should be on vialegacy issue tracker

But it is
https://github.com/RaphiMC/ViaLegacy/issues/3

**Comment by RaphiMC** [comment]
I can't add ViaFabric support even if I wanted to. ViaFabric does not expose the necessary API/Hooks to load ViaLegacy

**Comment by Outfit8TSB** [comment]
@kristibektashi quit fooling around dude, make the client use ViaFabricPlus instead.

**Comment by FlorianMichael** [comment]
@Outfit8TSB Please don't respond to an closed issue which is over a year old now.
