### ISSUE TITLE
Compiling the mod gets stuck on :viafabric-mc118:remapSourcesJar

### ISSUE THREAD

**Issue by Blayung** [ViaVersion/ViaFabric#222]
### `/viaversion dump` Output

not an in-game error

### Console Error

not an in-game error

### Bug Description

Basically, when I clone the mod and try to compile it it gets stuck on:
```
<========-----> 64% EXECUTING [1h 17m 57s]
> :viafabric-mc117:remapSourcesJar
> :viafabric-mc119:remapSourcesJar
> IDLE
> :viafabric-mc118:remapJar
> :viafabric-mc119:remapJar
> :viafabric-mc117:remapJar
> :viafabric-mc116:remapSourcesJar
> :viafabric-mc118:remapSourcesJar
```
It's been already running for 1h and it's stuck on :viafabric-mc118:remapSourcesJar since the counter was on 30min. I don't really know if it's just my pc being slow (which is very unlikely) or if it's and a problem with the mod.

### Steps to Reproduce

1. Clone the repo
2. Enter the directory that the repo was cloned to
3. Run `./gradlew build` (I'm on linux)
4. The error occurs.

### Expected Behavior

The mod compiles successfully.

### Checklist

- [x] I have checked if this is specific to ViaFabric platform, and doesn't happen when running it on other platforms (Paper/Sponge/Velocity/Waterfall).
- [x] I have included a ViaVersion dump.
- [x] If applicable, I have included a paste (**not a screenshot**) of the error.
- [x] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Blayung** [comment]
Actually, I ran it once again and it worked, but I will leave this as an issue just in case.

**Comment by Kichura** [comment]
Remapping can take some time so please be patient about it - Otherwise it would be the result of other applications / background services making your compiling time slower than expected; otherwise there isn't much we can do about it.
