### ISSUE TITLE
disable regsync

### ISSUE THREAD

**Issue by ZorkIsEmo** [ViaVersion/ViaFabric#225]
### `/viaversion dump` Output

https://dump.viaversion.com/d468386d80104409484bf18257b6b05c29f345eb7cdb28dd0703ad8a42612151

### Console Error

```
Put the paste.gg link or text here.
```

### Bug Description

cant be used with Universal Graves because it kicks 1.19.2 players from 1.19.3 servers with a registration issue on entity:camel

### Steps to Reproduce

login to 1.19.3 server which has universal graves installed with 1.19.2 client
get error

### Expected Behavior

should be let in

### Checklist

- [X] I have checked if this is specific to ViaFabric platform, and doesn't happen when running it on other platforms (Paper/Sponge/Velocity/Waterfall).
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Kichura** [comment]
3rd-party blocks/items/etc are not supported on viafabric.
