### ISSUE TITLE
Crashing minecraft after I press the viaversion button in the menu to enter the minecraft server

### ISSUE THREAD

**Issue by KOMPuteRSH4IK** [ViaVersion/ViaFabric#229]
I used 1.19.3 minecraft fabric 0.14.14 version and viafabric-0.4.9+19-main mod, ViaBackwards-4.5.1

The game crashed whilst mouseclicked event handler
Error: java.lang.NoSuchMethodError: 'void net.minecraft.class_4185.<init>(int, int, int, int, net.minecraft.class_2561, net.minecraft.class_4185$class_4241)'

**Comment by HowardZHY** [comment]
viafabric-0.4.9+19 is for 1.19.2 I think

**Comment by goteusz-maszyk** [comment]
same

**Comment by Kichura** [comment]
Closing this as 1.19.3 is not supported on viafabric, If it still causes issues with latest viafabric with 1.19.4 at same time; write a new comment here and it will be reopened.
