### ISSUE TITLE
Set ViaFabric to 1.19.2 but server still kicks me

### ISSUE THREAD

**Issue by ImGGAAVVIINN** [ViaVersion/ViaFabric#230]
### `/viaversion dump` Output

a

### Console Error

```
Put the paste.gg link or text here.
```

### Bug Description

I have set the version on ViaFabric is been set to 1.19.2 but server says outdated client

https://user-images.githubusercontent.com/68761233/223630712-34db7bc8-3c35-47e0-95fc-961c098a04e9.mp4

### Steps to Reproduce

1. Install ViaFabric 1.18.2
2. change version in ViaFabric menu to 1.19.2
3. Try to join a 1.19.2 server
4. Server will kick you with the reason outdated client

### Expected Behavior

Server should allow player to join since ViaFabric is been set to 1.19.2, which is the version that the server is running on.

### Checklist

- [X] I have checked if this is specific to ViaFabric platform, and doesn't happen when running it on other platforms (Paper/Sponge/Velocity/Waterfall).
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by HowardZHY** [comment]
You need install ViaBackwards in mods folder too if you want to connect to higher server versions.
