### ISSUE TITLE
ViaFabric 1.19.3 is not connecting to 1.19.2/1 servers

### ISSUE THREAD

**Issue by CombustibleLemonyade** [ViaVersion/ViaFabric#231]
### `/viaversion dump` Output

https://dump.viaversion.com/6aec7d8a433af9d5522197111ea1c919dae91b95112357678d260393b1534f52

### Bug Description

Connecting to a 1.19.2/1 server provides the error "multiplayer.disconnect.missing_public_key".
Adding the latest viaversion (ViaVersion-4.6.0) to the mods folder makes it worse, instead of providing that error it instead displays this when hovering over the connection bars: "Incompatible version!
VIA: 1.7.2-1.7.5"

### Steps to Reproduce

1. Open ViaFabric on 1.19.3 (version [main] ViaFabric 0.4.9+24-main)
2. Join a 1.19.2 server
3. Error appears

### Expected Behavior

You should be able to join said server.

### Checklist

- [x] I have checked if this is specific to ViaFabric platform, and doesn't happen when running it on other platforms (Paper/Sponge/Velocity/Waterfall).
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Munchax10** [comment]
Same bug is working on 1.19.4 when trying to connect to a 1.19.2 server.

**Comment by FlorianMichael** [comment]
Secure chat is not implemented in ViaFabric, you can alternatively look at ViaProxy or ViaFabricPlus, or alternatively you can disable secure chat on the server.
