### ISSUE TITLE
can't connect to 1.19.4 for 1.19.3

### ISSUE THREAD

**Issue by alien-sunset** [ViaVersion/ViaFabric#232]
### `/viaversion dump` Output

https://dump.viaversion.com/24a57d070d3c317c64ff1136aa1a151dd758ffed2783474ebf3eb0bb55458569

### Console Error

```
Put the paste.gg link or text here.
```

### Bug Description

newest version of viafabric for 1.19.3 (0.4.9+24) along with newest versions of viaversion/backwards (4.6.1) will not give option to join 1.19.4  or 1.19.2 servers.

updating to (0.4.9+29) does not work because it requires client to be 1.19.4

### Steps to Reproduce

download latest version of viaversion/backwards onto 1.19.3 client along with latest 1.19.3 version of via fabric.

open multiplayer tab in hemiscreen, 1.19.2 servers and 1.19.4 servers will be crossed out

### Expected Behavior

1.19.2 and 1.19.4 servers would allow connection 

### Additional Server Info

1.19.2 server is a fabric server, 1.19.4 server is a paper server

### Checklist

- [X] I have checked if this is specific to ViaFabric platform, and doesn't happen when running it on other platforms (Paper/Sponge/Velocity/Waterfall).
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Kichura** [comment]
1.19 - 1.19.3 is unsupported in viafabric, Please update to 1.19.4 whenever possible; otherwise if you wish to make it work on older viafabric copies that requires the older 1.19.x minor version then you must implement viaversion 4.6.x/4.7.x support yourself.
