### ISSUE TITLE
Crashes on 1.19.4 when joining any world

### ISSUE THREAD

**Issue by electron271** [ViaVersion/ViaFabric#236]
### `/viaversion dump` Output

I was unable to join a singleplayer world either, sorry

### Console Error

https://paste.gg/p/anonymous/7b9b39bb94884035b32a146ac6dd1296

### Bug Description

Joining `constantiam.net` (a 1.19.2 server) on a 1.19.4 client causes the game to crash.

### Steps to Reproduce

1. Login with a 1.19.4 client
2. Log into the server
3. Crash

### Expected Behavior

Not have it crash

### Checklist

- [X] I have checked if this is specific to ViaFabric platform, and doesn't happen when running it on other platforms (Paper/Sponge/Velocity/Waterfall).
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by creeper123123321** [comment]
```
java.lang.RuntimeException: Mixin transformation of me.jellysquid.mods.sodium.client.render.chunk.compile.pipeline.BlockRenderer failed
```
seems to be related to sodium

**Comment by Kichura** [comment]
Not a viafabric issue as meteor conflicts with sodium.
