### ISSUE TITLE
can't connect 1.7.10 servers with this mod. tried different minecraft/mod versions

### ISSUE THREAD

**Issue by apathytheme** [ViaVersion/ViaFabric#237]
### `/viaversion dump` Output

https://dump.viaversion.com/076e4227f71f659ff22efbe090d5c7448a44843d371325b5c5cd5ad8aac3f13d

### Console Error

-

### Bug Description

please help, idk maybe it is unsupported version but I can't find any information

### Steps to Reproduce

just using the mod

### Expected Behavior

I want to join 1.7.10 server with 1.12.2+ version.

### Additional Server Info

-

### Checklist

- [x] I have checked if this is specific to ViaFabric platform, and doesn't happen when running it on other platforms (Paper/Sponge/Velocity/Waterfall).
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by apathytheme** [comment]
> 1.7 Servers aren't supported

are there any other ways to connect 1.7 servers with newer versions?

**Comment by apathytheme** [comment]
are there any other ways to connect 1.7 servers with newer versions? 

> 1.7 Servers aren't supported

**Comment by RaphiMC** [comment]
No official ways. You could use https://github.com/RaphiMC/ViaProxy which is an external proxy which allows you to join every minecraft version.

**Comment by apathytheme** [comment]
> No official ways. You could use https://github.com/RaphiMC/ViaProxy which is an external proxy which allows you to join every minecraft version.

ok thanks
