### ISSUE TITLE
Fails on e4mc and Essential regardless of client-side modes

### ISSUE THREAD

**Issue by Kichura** [ViaVersion/ViaFabric#247]
### `/viaversion dump` Output

https://dump.viaversion.com/98fd26684595cf16bd6a36c39d498ca4051e74a659e32010566748775b1c82bb

### Console Error

*(No console errors were discovered during tests)*

### Bug Description

When opening the singleplayer to LAN whilst ViaFabric is deployed - Players are able to join properly using the required extensions that the server owner has also included in their modpack(s) which is ViaBackwards and optionally ViaRewind,

However when combining it with e4mc / essential mod, Both will cancel out ViaFabric's translation attempts and instead fallback to vanilla's "Outdated Client!" behavior instead.

### Steps to Reproduce

1. Get a 1.19.4 client and 1.18.2 client respectively,
2. Deploy ViaFabric, ViaBackwards and either e4mc or essential mod onto the 1.19.4 client,
3. Open any world on the 1.19.4 client and request it to be opened to LAN,
4. Attempt to join the server using 1.18.2 client by using e4mc's IP or essential's friends system,
5. Expect a kick from there.

### Expected Behavior

ViaFabric is able to communicate with e4mc and essential mod properly and continues translating.

### Additional Server Info

1. The server is not running on a proxy,
2. Two tests were platformed so far:

ViaFabric, ViaBackwards with e4mc,
and same thing again as above but instead essential mod was used.

3. Client-Side was active during these attempts.

### Checklist

- [X] I have checked if this is specific to ViaFabric platform, and doesn't happen when running it on other platforms (Paper/Sponge/Velocity/Waterfall).
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Kichura** [comment]
Something else i will have to point out in this entire issue:

1. Essential mod is entirely closed-source, meaning it will be difficult to troubleshoot this mod due to how complicated it is,
2. e4mc is open source but on dedicated GitTea instance, But this one reveals a generated sub-domain upon opening to LAN.

**Comment by cootshk** [comment]
try using [world host](https://modrinth.com/mod/world-host)

**Comment by Kichura** [comment]
> try using [world host](https://modrinth.com/mod/world-host)
> ### Make sure to open mod menu config and turn off `try Upnp`

This mod works properly without issues during testing.

**Comment by Kichura** [comment]
Since these two mods essentially use a different method for connectivity, will not be fixed.
