### ISSUE TITLE
It can't work at 1.19.4

### ISSUE THREAD

**Issue by Walkersifolia** [ViaVersion/ViaFabric#258]
### `/viaversion dump` Output

https://dump.viaversion.com/0e478dcdde9962c30a0fccb9f1a48099914ad09a577fdb4fab399e76680835d7

### Console Error

```
Put the paste.gg link or text here.
```

### Bug Description

When I using the 1.19.4 client, I can't get in any server, the screen show that
![1PF4YZJOKWFZM)L)GMY1O0I](https://github.com/ViaVersion/ViaFabric/assets/129571444/9abd270a-a605-4a30-b229-f87e726ed5d7)

### Steps to Reproduce

login in with the 1.19.4 client
try to entry the server

### Expected Behavior

I want to entry multiplayer server

### Checklist

- [ ] I have checked if this is specific to ViaFabric platform, and doesn't happen when running it on other platforms (Paper/Sponge/Velocity/Waterfall).
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Kichura** [comment]
Either a third-party mod or server itself has plugins on it that viafabric has trouble working with properly, Please verify if issue also happens without any other mods active except fabric api.

**Comment by FoxPodZ** [comment]
I had the same issue. The issue for me was something related to ReplayMod version 2.6.13 (1.19.4). I downgraded to version 2.6.12 (1.19.4)

**Comment by Walkersifolia** [comment]
> I had the same issue. The issue for me was something related to ReplayMod version 2.6.13 (1.19.4). I downgraded to version 2.6.12 (1.19.4)

OK, I will test it right now, thank you

**Comment by Walkersifolia** [comment]
> Either a third-party mod or server itself has plugins on it that viafabric has trouble working with properly, Please verify if issue also happens without any other mods active except fabric api.

The server is a Vanilla server, I will check the client

**Comment by Kichura** [comment]
> > Either a third-party mod or server itself has plugins on it that viafabric has trouble working with properly, Please verify if issue also happens without any other mods active except fabric api.
> 
> The server is a Vanilla server, I will check the client

Can you test with latest viafabric and viabackwards from github actions just to be sure it persists there too? *(and also don't include third-party mods on your client except fabric api)*

**Comment by Walkersifolia** [comment]
Thank you, I got it, I will try it tomorrow, and I will tell you the result, but I have a exam tomorrow and I'm in GMT+8 time zone, so it will be later for you ,sorry

**Comment by MassivebutterpapperCodes** [comment]
Same issue i'm running Meteor Client with ViaFabric. well, meteor makes sence...

**Comment by MassivebutterpapperCodes** [comment]
English view:
![Capture](https://github.com/ViaVersion/ViaFabric/assets/134733276/4efcd867-318a-4dbc-b2aa-f1545b352e5f)

**Comment by MassivebutterpapperCodes** [comment]
> > > Either a third-party mod or server itself has plugins on it that viafabric has trouble working with properly, Please verify if issue also happens without any other mods active except fabric api.
> > 
> > 
> > The server is a Vanilla server, I will check the client
> 
> Can you test with latest viafabric and viabackwards from github actions just to be sure it persists there too? _(and also don't include third-party mods on your client except fabric api)_

Sure!
![files](https://github.com/ViaVersion/ViaFabric/assets/134733276/e0750c27-e94a-485e-add0-54b24c0dd25e)
![files out](https://github.com/ViaVersion/ViaFabric/assets/134733276/49709700-b4a1-47ec-b035-f2c1dd78bb25)
![loading](https://github.com/ViaVersion/ViaFabric/assets/134733276/8047ae54-f6b2-4df4-883b-042aa09f9c51)
![still](https://github.com/ViaVersion/ViaFabric/assets/134733276/3b4b15cc-4f70-4ce6-be98-47852deb2651)

**Comment by MassivebutterpapperCodes** [comment]
oh wait u said with viabackwards

**Comment by MassivebutterpapperCodes** [comment]
> > > Either a third-party mod or server itself has plugins on it that viafabric has trouble working with properly, Please verify if issue also happens without any other mods active except fabric api.
> > 
> > 
> > The server is a Vanilla server, I will check the client
> 
> Can you test with latest viafabric and viabackwards from github actions just to be sure it persists there too? _(and also don't include third-party mods on your client except fabric api)_

Sure! These are the files:
![files](https://github.com/ViaVersion/ViaFabric/assets/134733276/184c4abd-7604-4490-ab24-aad155b0b28e)
ima take them out
![files out](https://github.com/ViaVersion/ViaFabric/assets/134733276/27c703ae-40e1-44cc-8b55-d16cd8979f6f)
restarting mc:
![loading](https://github.com/ViaVersion/ViaFabric/assets/134733276/65df27b6-24d2-47ec-8285-880e284154b9)
and still:
![still](https://github.com/ViaVersion/ViaFabric/assets/134733276/ba827001-f4d0-48a5-a7f4-41338de6d534)

**Comment by MassivebutterpapperCodes** [comment]
Without ViaBackwards:
files:
![files](https://github.com/ViaVersion/ViaFabric/assets/134733276/bff9c4e1-c59b-4cf9-a7dc-505ed5d46822)
files out:
![files out](https://github.com/ViaVersion/ViaFabric/assets/134733276/6a48f547-e86e-47a8-af44-950c0040892e)
launching:
![loading](https://github.com/ViaVersion/ViaFabric/assets/134733276/c635c715-0bc5-497c-9328-36df338164c1)
and still:
![still](https://github.com/ViaVersion/ViaFabric/assets/134733276/fc23fcc1-bf0d-4da9-96c7-501b051b74c1)
With ViaBackwards:
![MCONLINE!](https://github.com/ViaVersion/ViaFabric/assets/134733276/0bfdb8c3-096a-4804-bb5a-4fa13c9d6e01)
It works, im on minecraft online in 1.19.4 Server IP Btw: minecraftonline.com If u join it will say a 1.12.2 error. Prove this is 1.19.4 is: Check the window title

**Comment by Kichura** [comment]
Does this problem persist with latest viafabric?

**Comment by Walkersifolia** [comment]
> Does this problem persist with latest viafabric?

Nope, I have never meet this problem again.
