### ISSUE TITLE
Mod for 1.19.2. For playing 1.19.2 on 1.19.4 servers

### ISSUE THREAD

**Issue by lynrayy** [ViaVersion/ViaFabric#262]
Please build new viafabric for playing on 1.19.4 servers from 1.19.2 minecraft. It is 1.19.3 latest on 1.19.2!

**Comment by lynrayy** [comment]
This is a lie 
![image](https://github.com/ViaVersion/ViaFabric/assets/59417884/9067bb7d-3182-43ad-b479-3831653cb23f)

**Comment by Username404-59** [comment]
I do not think the table needs to be updated, as you can just use a more recent version of ViaVersion to be able to join 1.19.4 servers (as far as I'm aware)

**Comment by lynrayy** [comment]
> I do not think the table needs to be updated, as you can just use a more recent version of ViaBackwards to be able to join 1.19.4 servers (as far as I'm aware)

It not works. I have latest viaversion and viabackwards in mods folder and i just can't set 1.19.4 in version field (in game)
