### ISSUE TITLE
Cant join from 1.19.4 version to 1.20.1

### ISSUE THREAD

**Issue by TheFirstPlaceCoder** [ViaVersion/ViaFabric#264]
### `/viaversion dump` Output

/

### Console Error

```
I cant join from 1.19.4 minecraft version to 1.20.1 server version. I use it, but i cant anyway
```

### Bug Description

I cant join from 1.19.4 minecraft version to 1.20.1 server version. I use it, but i cant anyway

### Steps to Reproduce

1. Update VIaFabric for joining from 1.19.4 to NEWEST version of minecraft

### Expected Behavior

/

### Additional Server Info

/

### Checklist

- [X] I have checked if this is specific to ViaFabric platform, and doesn't happen when running it on other platforms (Paper/Sponge/Velocity/Waterfall).
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by HowardZHY** [comment]
You also need ViaBackwards

**Comment by Kichura** [comment]
1. The issue template is not followed properly,
2. Install latest viafabric from github actions and also latest viabackwards too.
