### ISSUE TITLE
Can't work with krypton 0.2.3

### ISSUE THREAD

**Issue by lonelysam3** [ViaVersion/ViaFabric#266]
### `/viaversion dump` Output

the server can't start!

### Console Error

```
Put the paste.gg link or text here.
```
https://paste.gg/p/anonymous/9ee22818474c4ecf8629e408ff33593f

### Bug Description

https://github.com/astei/krypton/issues/103

### Steps to Reproduce

1.install viafabric 0.4.10+40-main with krypton 0.2.3 and fabric api
2.start the server

### Expected Behavior

server should not crash

### Checklist

- [X] I have checked if this is specific to ViaFabric platform, and doesn't happen when running it on other platforms (Paper/Sponge/Velocity/Waterfall).
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Kichura** [comment]
Not a crash as we told people to remove it from their clients due to it no longer functioning correctly on viafabric itself, However there is a commit on latest CI build to see if the compat script works properly - In short, There are two ways to solve it:

1. Get rid of krypton,
2. Keep it but update viafabric to latest github build.

**Comment by lonelysam3** [comment]
ah,just because the author fo krypton told me it's not krypton's problem
and as you can see i had updated viaversion to the latest github build in my log.
so you meant i can't use viafabric with krypton,right?

**Comment by Kichura** [comment]
> ah,just because the author of krypton told me it's not krypton's problem and as you can see i had updated viaversion to the latest github build in my log. so you meant i can't use viafabric with krypton,right?

In the official build, We initally said "yeah this is not going to work out well" and blocked it out from working with our mod which happens to be the same process that ViaFabricPlus also uses - But creeper has pushed out a commit that re-adds compatibility for it in github actions itself that people try out for themselves.
