### ISSUE TITLE
can not open Smithing Table UI when c-side is 1.20+

### ISSUE THREAD

**Issue by bAdOoWindy** [ViaVersion/ViaFabric#271]
### `/viaversion dump` Output

unnecessary

### Console Error

unnecessary

### Bug Description

i'm using 1.20 to play 1.17 server
i can not open Smithing Table UI to updata my diamond equip

### Steps to Reproduce

use 1.20 minecraft
login to 1.17 server
can not open Smithing Table UI

### Expected Behavior

make it work !

### Additional Server Info

any server not using Smithing Template

### Checklist

- [ ] I have checked if this is specific to ViaFabric platform, and doesn't happen when running it on other platforms (Paper/Sponge/Velocity/Waterfall).
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Kichura** [comment]
Since you refused to give out the viaversion dump, this is considered invalid.
