### ISSUE TITLE
Can't connect to 1.20.1 ViaFabric server with vanilla 1.20.2 client

### ISSUE THREAD

**Issue by SusStew** [ViaVersion/ViaFabric#273]
### `/viaversion dump` Output

https://dump.viaversion.com/34ffbafcc861c39e2d9abe9a1921d9a77e20bcef15e69238395b44b19a297f23

### Bug Description

I'm trying to host a server that's on 1.20.1 and allow it to be connected to with a more recent client. I thought ViaVersion was supposed to be used for this but when I try it it doesn't work. Depending on which version of ViaFabric/ViaVersion I have installed it either doesn't launch the server and says the version is incompatible or the player joining times out.

### Steps to Reproduce

1. Install ViaFabric that is compatible with 1.20.1 along with latest ViaVersion
2. Player on vanilla 1.20.2 attempts to join
3. The screen gets stuck on "Joining world..." for a minute or two
4. Eventually the connection times out

### Expected Behavior

Vanilla 1.20.2 client should join server as normal

### Checklist

- [ ] I have checked if this is specific to ViaFabric platform, and doesn't happen when running it on other platforms (Paper/Sponge/Velocity/Waterfall).
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by rayhanhamada93** [comment]
1.20.2 is also unable to connect to 1.20 server using the latest available version of viafabric that support 1.20, while the latest viafabric that labeled as 1.20.2 crashes the 1.20 server

**Comment by ThatBlockyPenguin** [comment]
Also having this issue. Dump: https://dump.viaversion.com/b8b08ac948e1b3abada6c3e457805b9b11292537967e04bf05e30b20c5ceee7d

**Comment by Kichura** [comment]
> Also having this issue (1.20.1 server, 1.20.2 client). Dump: [dump.viaversion.com/b8b08ac948e1b3abada6c3e457805b9b11292537967e04bf05e30b20c5ceee7d](https://dump.viaversion.com/b8b08ac948e1b3abada6c3e457805b9b11292537967e04bf05e30b20c5ceee7d)

Update viaversion to 4.8.1.

**Comment by imagelesskink** [comment]
> > Also having this issue (1.20.1 server, 1.20.2 client). Dump: [dump.viaversion.com/b8b08ac948e1b3abada6c3e457805b9b11292537967e04bf05e30b20c5ceee7d](https://dump.viaversion.com/b8b08ac948e1b3abada6c3e457805b9b11292537967e04bf05e30b20c5ceee7d)
> 
> Update viaversion to 4.8.1.

What about ViaFabric users?

**Comment by Hi-ImKyle** [comment]
> Update viaversion to 4.8.1.
This is a ViaFabric issue. Isn't the point of ViaFabric to implement ViaVersion for modded servers? How are we supposed to update that?

**Comment by Faris90** [comment]
any luck?

**Comment by Kichura** [comment]
Since 1.20.1 is by default unsupported, will not be worked on - 1.19.4 however is supported.

**Comment by Faris90** [comment]
> Since 1.20.1 is by default unsupported, will not be worked on - 1.19.4 however is supported.

What's stopping y'all
