### ISSUE TITLE
Viafabric with 1.20.2 support on 1.20 please? 🥺

### ISSUE THREAD

**Issue by RealKomander** [ViaVersion/ViaFabric#276]
I run a fabric 1.20 server and really need to add a support to 1.20.2. A bunch of mods that I use are still not updated to newer versions, so it would be much more helpful to get a viafabric release. Does anyone have the same problem? Do I miss anything? Is it even physically possible to release a version like this?

**Comment by Kichura** [comment]
You can update to 1.20.1 safely using viafabric 40-main via modrinth but either than that, 1.20.0 itself will not be considered.
