### ISSUE TITLE
Crash with latest build of ViaFabric & ViaBackwards

### ISSUE THREAD

**Issue by RoblKyogre** [ViaVersion/ViaFabric#279]
### `/viaversion dump` Output

N/A, unable to run command

### Console Error

https://pastebin.com/tA6zVuj1

### Bug Description

The server crashes almost immediately when ViaBackwards is in the mods folder. Removing it from the mods folder resolves the issue.

### Steps to Reproduce

1. Install Fabric Server
2. Place both ViaFabric and ViaBackwards into `mods` folder
3. Run the server

### Expected Behavior

The server should load successfully and allow 1.20.1 or earlier clients to connect.

### Additional Server Info

Using the latest version of mods as taken from Modrinth:
- https://modrinth.com/mod/viafabric/version/0.4.11+49-dev
- https://modrinth.com/plugin/viabackwards/version/4.9.0-23w44a-SNAPSHOT+61

The issue report form recommends Not Enough Crashes so that is included, but I can reproduce the issue without it.

### Checklist

- [ ] I have checked if this is specific to ViaFabric platform, and doesn't happen when running it on other platforms (Paper/Sponge/Velocity/Waterfall).
- [ ] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Kichura** [comment]
Update to latest via* builds, also 1.20.2 fabric servers with fabric api in it is currently busted anyways.
