### ISSUE TITLE
1.20.2 server crashes on startup with viabackwards installed

### ISSUE THREAD

**Issue by Skywalker8510** [ViaVersion/ViaFabric#283]
### `/viaversion dump` Output

server is crashing no link is able to be generated.

### Console Error

```
https://mclo.gs/XZzoJcI
```

### Bug Description

1.20.2 server crashes on startup with viabackwards installed

### Steps to Reproduce

make a fabric mc server
put viafabric and viabackwards in the mods folder any combination of 1.20.2 versions will give the same error iv tried.
try to start the server and it will fail to start

### Expected Behavior

server starts up normally

### Additional Server Info

i use this server as a lobby for velocity. has the following mods fabric proxy lite, proxy command fabric, floodgate, and obviously viafabric and viabackwards.

### Checklist

- [X] I have checked if this is specific to ViaFabric platform, and doesn't happen when running it on other platforms (Paper/Sponge/Velocity/Waterfall).
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Kichura** [comment]
Update viafabric and viabackwards to latest dev builds, also install latest viaversion jar to mods folder too.

**Comment by RealKomander** [comment]
Downloading latest dev build available for 1.20.2 doesn't help. All the newer builds that aren't made with 1.20.2 in mind don't want to load on this version

**Comment by Kichura** [comment]
It's because 1.20.2 support was dropped in favor of 1.20.4.
