### ISSUE TITLE
Fabric client of 1.20.1 cannot join the server of fabric 1.20.2

### ISSUE THREAD

**Issue by yizexiaomu** [ViaVersion/ViaFabric#287]
### `/viaversion dump` Output

https://dump.viaversion.com/b43a49c5d3bdd5049e011a3bad73cd2941dccf5b19ab23450c8542f2020e280d

### Console Error

https://mclo.gs/r8ncoiH

### Bug Description

Using the fabric1.20.1 client that only installs viafabricplus-2.8.7 and fabric-api-0.84.0+1.20.1, it is not possible to join the 1.20.2 server that only installs fabric-api-0.90.0+1.20.2, Viafabric-0.4.11+50-dev, and ViaVersion 4.9.3-SNAPSHOT. The image below is evidence and error messages for joining the server
Note: The network compression threshold of server.properties has been changed to a larger number, and the max pps and tracking period in the configuration file of viversion.yml have been changed to -1
![QQ截图20231209213926](https://github.com/ViaVersion/ViaFabric/assets/143194618/5b65fa30-55e4-48a4-9df5-7048aacf157e)
![QQ截图20231209213952](https://github.com/ViaVersion/ViaFabric/assets/143194618/40885e44-f7b5-49e1-89d4-832be0354cad)
![QQ截图20231209214130](https://github.com/ViaVersion/ViaFabric/assets/143194618/427891d3-3e61-4b4b-baa0-f79196f5318e)

### Steps to Reproduce

1. Start the 1.20.2 fabric server
2. Start the 1.20.1 fabric client
3. Client joining server
4. Unable to access server
Note: Testing has been conducted on different computers on the same network as the client and server, as well as on the same computer environment. Testing has also been conducted on different networks, but access to the server is not possible

### Expected Behavior

Can join the server

### Additional Server Info

The server not use any proxy.The server did not use mods other than fabric api-0.90.0+1.20.2, ViaFabric 0.4.11+50-dev, and ViaVersion 4.9.3-SNAPSHOT.I am not using client-side mode

### Checklist

- [X] I have checked if this is specific to ViaFabric platform, and doesn't happen when running it on other platforms (Paper/Sponge/Velocity/Waterfall).
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Kichura** [comment]
1.20.2 is no longer supported, Please update to 1.20.3/1.20.4.

**Comment by yizexiaomu** [comment]
Many mods on my server and client have not been updated to 1.20.3/1.20.4, so the only solution now is to wait for these mods to be updated?

**Comment by Kichura** [comment]
> Many mods on my server and client have not been updated to 1.20.3/1.20.4, so the only solution now is to wait for these mods to be updated?

Yes since 1.20.2 is quite buggy in terms of client support - You could attempt to update fabric API but i cannot be sure if this would resolve your problem that way. *(+ 1.19 and older clients have yet to be fixed due to either chat reporting system or something else breaking them)*

**Comment by yizexiaomu** [comment]
I have just tried to update the fabric API to the latest version, but the problem has not been resolved, so all I can do now is wait
Thank you again for your answer

**Comment by HowardZHY** [comment]
You can install ViaBackwards on the 1.20.2 Fabric server

**Comment by yizexiaomu** [comment]
I have also tried, but there are still problems

**Comment by HowardZHY** [comment]
https://modrinth.com/mod/viavanillaplus try this mod

**Comment by yizexiaomu** [comment]
I have also tried,still not work
