### ISSUE TITLE
Please fix incompatibility with Fabric Proxy Lite!

### ISSUE THREAD

**Issue by RealKomander** [ViaVersion/ViaFabric#289]
### `/viaversion dump` Output

https://dump.viaversion.com/c7c45d78dc76b0301558a31d36587dd8364768e655fd54187f7c9f36baa9a9ae

### Console Error

`[19:28:12] [Server thread/INFO]: com.mojang.authlib.GameProfile@487fc80c[id=b18a2b65-0131-4c4f-926c-f81305475690,name=RealKomander,properties={textures=[Property[name=textures, value=ewogICJ0aW1lc3RhbXAiIDogMTcwMzAwMzI4Mjg4MCwKICAicHJvZmlsZUlkIiA6ICJiMThhMmI2NTAxMzE0YzRmOTI2Y2Y4MTMwNTQ3NTY5MCIsCiAgInByb2ZpbGVOYW1lIiA6ICJSZWFsS29tYW5kZXIiLAogICJzaWduYXR1cmVSZXF1aXJlZCIgOiB0cnVlLAogICJ0ZXh0dXJlcyIgOiB7CiAgICAiU0tJTiIgOiB7CiAgICAgICJ1cmwiIDogImh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvOWVhYzA0YzUxYjMyMDMxODliMTkxOTc5ZjMyZTg0NDJlZmQ4MzhhYWVlNDM4ZDZiNGU5NWJhYTYxOGFmYzNlYyIKICAgIH0sCiAgICAiQ0FQRSIgOiB7CiAgICAgICJ1cmwiIDogImh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvMjM0MGMwZTAzZGQyNGExMWIxNWE4YjMzYzJhN2U5ZTMyYWJiMjA1MWIyNDgxZDBiYTdkZWZkNjM1Y2E3YTkzMyIKICAgIH0KICB9Cn0=, signature=GT+MZsmdtOJ6Gv8b9dXYyZotpodIbPxePjscSKSnWvJbvfBJEQpJk398mfQhjia1gnU4e6wdn7rVB3pwPpCeql32R+kpdKhSI08VFPhEb0gdgdeB20FbFtdSsTlnBkPGOtwomnytyMAaXn5BkPtBrHgmuXz2mvX5Bn34WlulescwNHdxqAn+qIxoxf2DgVT63LvFK3y3AUnSbwLQtgsU606Qla7Gx9cxNbLMao7tqp8MLEgmlAr8tDuxg1MXkjXkm47c8sxy2PsNgdZoeKvGxLsU0cxM8qP+1WqZDHRQhJyPnAqDbhERYm8RkxSbENSk14wmGKO9XcLiw7LzPJCyNy9BJRJyaFdq5E8/OloiBx0BotZDBuSFyBZY8K6/ebSGp3KL/bgSqkeTbSG7146KBODbHSVH2IdXFz+uFKjWXetAyTbgOqI3gLGE7uYTHoV5MKkdQghjLSJzUrRV9FU4MpQwUq4T98JJ/21h7IMj5O2BeRq/nsitcAzugP1r3eb+PPmkPXbo9XX1XvLjxO0mkkjCC+PG1Hx/3I0CVOdCLUnv8Ow/yf+n5BqtgTI4sKAAKj8vYOEtV5GJZIYkvIBGfI8e8GhmnXheKzlP5yt8XRYQCLMn/Apw94qEzLbYf34if/9WpejDm+qh3FDkx6AwWIP/bSzdMoOV4RQw/z6P0/0=]]}] lost connection: Disconnected
` 

### Bug Description

Whenever I try joining from 1.20.1, I get the error. Native version works just fine.

I don't know what exactly causes this issue, I am sending it to both ViaVersion and Fabric Proxy Lite. I've had enough of this sort of errors, this is not the first one.
Sorry if I already reported it to somewhere else - this whole thing is a complete mess, mojang broke everything in 1.20.2, I haven't managed to make a successfully running server with full compatibility since the very release of this stupid version. 

https://github.com/OKTW-Network/FabricProxy-Lite/issues/71

### Steps to Reproduce

Download everything that I mentioned on a fabric 1.20.2 server and a velocity 3.2.0 snapshot 296

Fabric mods:
- fabric-api-0.91.2+1.20.2
- FabricProxy-Lite-2.7.0
- ViaBackwards-4.10.0-23w51b-SNAPSHOT
- ViaFabric-0.4.11+50-dev
- ViaVersion-4.10.0-23w51b-SNAPSHOT

Velocity plugins:
- limboapi-1.1.17
- limboauth-1.1.13
- LuckPerms-Velocity-5.4.62
- Remember.Me-1.2.3
- SlashHub-1.2

### Expected Behavior

Successful support of 1.20.1. 

### Additional Server Info

I use latest velocity build 296.

### Checklist

- [X] I have checked if this is specific to ViaFabric platform, and doesn't happen when running it on other platforms (Paper/Sponge/Velocity/Waterfall).
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by RealKomander** [comment]
This is what, the 3rd gibberish looking issue? I'm terribly sorry if I have already reported it and forgot about it, I've reported more than 10 errors regarding several mods and I'm starting to go insane

**Comment by RealKomander** [comment]
Why? And what's the point of the plugin for extending older versions if it doesn't support older versions? Which versions are supported?

**Comment by Kichura** [comment]
> Why? And what's the point of the plugin for extending older versions if it doesn't support older versions? Which versions are supported?

1.14.4, 1.15.2, 1.16.5, 1.17.1, 1.18.2, 1.19.4 and 1.20.4 *(soon to be superseded with 1.20.5)* are all supported - older minor versions are not and never will be by default as they are exhaustive to work on + updating the internal classes in viafabric would break support for the older minor versions anyways.
