### ISSUE TITLE
BossBar still not showing up with fabric 1.14.4 client on spigot 1.8.8

### ISSUE THREAD

**Issue by RaphiMC** [ViaVersion/ViaFabric#29]
**Describe the bug, provide any errors**
Setup: 1.14.4 Fabric with ViaFabric installed.
If you summon a wither the bossbar will not appear on the ViaFabric client.

**How can we reproduce it?**
1. Select version 1.8 in ViaFabric and join a spigot 1.8.8 server
2. Summon a wither
3. No BossBar will appear

**Expected behaviour**
A BossBar showing the health of the wither

**Screenshots**
http://prntscr.com/t6pryu

**ViaVersion Dump:**
- Can't do that in ViaFabric.
I use the latest ViaVersion and ViaFabric version (downloaded 26.06.2020)

**Additional server info**
No plugins were present on the test-server.

**Comment by RaphiMC** [comment]
I created a new issue because the old one got closed and the bug remained

**Comment by Username404-59** [comment]
So did you update ViaVersion?

**Comment by creeper123123321** [comment]
Are you using the latest ViaVersion from ci.viaversion.com?

**Comment by RaphiMC** [comment]
Yes
