### ISSUE TITLE
ViaFabric crashes on 1.17.1 during boot sequence

### ISSUE THREAD

**Issue by Kichura** [ViaVersion/ViaFabric#290]
### `/viaversion dump` Output

(Not possible as client crashes on boot)

### Console Error

The crash logs can be found [here](https://pastebin.com/raw/gCWW5As9).

### Bug Description

When installing latest viafabric to the 1.17.1 client, the client will just instantly crash and says there's something wrong with the debugging mixin.

### Steps to Reproduce

1. Create a fabric 1.17.1 client with fabric api on it,
2. Install latest viafabric on it,
3. Start up the client,
4. Expect a possible crash from here.

### Expected Behavior

1.17.1 loads up properly with no issues.

### Additional Server Info

1. No proxies were used, *(in fact how is this possible?)*
2. Fabric API, ViaBackwards and ViaFabric,
3. I am using client-side mode.

### Checklist

- [X] I have checked if this is specific to ViaFabric platform, and doesn't happen when running it on other platforms (Paper/Sponge/Velocity/Waterfall).
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by FlorianMichael** [comment]
Thanks for reporting
