### ISSUE TITLE
Ошибка сервер 1.20.1 подключение: 1.20.1 Клиент: 1.20.4

### ISSUE THREAD

**Issue by Internativ** [ViaVersion/ViaFabric#291]
### `/viaversion dump` Output

https://dump.viaversion.com/9ca498ef98a87b702a3cf2d44e825d33078ab054b0b463c458823f47d9c85ea6

### Console Error

![image](https://github.com/ViaVersion/ViaFabric/assets/154490554/393b83c3-d228-4c18-a5ba-d6b75e90c40f)

### Bug Description

Хотел зайти на сервер 1.20.1 с подключения 1.20.1 на версии 1.20.4 

### Steps to Reproduce

1. Войти с клиентом 1.20.1 2. На сервер не заходит.

### Expected Behavior

Игра не должна крашится.

### Additional Server Info

Да.

### Checklist

- [X] I have checked if this is specific to ViaFabric platform, and doesn't happen when running it on other platforms (Paper/Sponge/Velocity/Waterfall).
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Kichura** [comment]
1. Обновите ViaBackwards,
2. Если обновление не удалось, то, скорее всего, проблема связана с плохим сторонним плагином.
3. Этот отчет находится не в том репозитории.
