### ISSUE TITLE
Server connection Screen cancel button unresponsive

### ISSUE THREAD

**Issue by MrKinau** [ViaVersion/ViaFabric#302]
### `/viaversion dump` Output

Command does not exist

### Console Error

https://mclo.gs/Ft1DLag

### Bug Description

After enabling ViaVersion using the button in the server selection screen, every attempt to cancel a connection will take much longer. It's hard to describe, but I made a video to demonstrate it: https://youtu.be/DMvRyInTGaA 

Additional Information:
This bug appears to happen since 1.20.3 (I've just tested with my old 1.20.1 instance 0.4.10+40-main and the bug wasn't present, also tested with 0.4.11+50-dev (1.20.2) and the bug was present).
The connection screen closes exactly at the same time as the log prints:
`[20:49:40] [Server Connector #2/WARN]: Could not auto-detect protocol for google.com/**.**.**.**:25565 java.util.concurrent.TimeoutException`

### Steps to Reproduce

1. Enable ViaVersion
2. Connect to a server (ideally a server where the connection takes very long, e.g. google.com, no MC server, but it tries to connect very long)
3. Click on cancel during connection

### Expected Behavior

The server selection should almost immediately appear after clicking on cancel

Observed behaviour: The connection screen stays on top and it looks like it's lagging.

### Checklist

- [X] I have checked if this is specific to ViaFabric platform, and doesn't happen when running it on other platforms (Paper/Sponge/Velocity/Waterfall).
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Kichura** [comment]
Confirmed bug.

**Comment by FlorianMichael** [comment]
Does this issue only appear when using AUTO (auto detection of the server version) as version? It seems like auto detect is still running even after pressing Cancel (and that's causing the lagg.)

**Comment by MrKinau** [comment]
No. I've tested with `AUTO` and `1.20/1.20.1` both were laggy.
