### ISSUE TITLE
Polymer + ViaFabric 1.20.4 seems to not omit experimental mobs, blocks, items for Fabric 1.20.2 clients

### ISSUE THREAD

**Issue by Ampflower** [ViaVersion/ViaFabric#309]
### `/viaversion dump` Output

https://dump.viaversion.com/192aa3afd02a621ab569400d1c62c30f07963758c2f8c0a477999b3ac5d9b7b0

### Console Error

[From server](https://mclo.gs/unxnNgM) - not particularly helpful for more than versions

[From client](https://mclo.gs/5LbpBB0)

### Bug Description

Fabric 1.20.2 clients cannot join a ViaFabric 1.20.4 server due to registry syncing.

Note, duplicated this issue from Patbox/polymer#109, originally reported on Modflower/Polysit#7.

### Steps to Reproduce

- On server:
  - Use Minecraft 1.20.4
  - Install Fabric API, ViaFabric, ViaRewind, Polymer, any Polymer-based mod (i.e. Polysit, Polyfactory)
    - It seems that any registry modification is required, as bare Polymer doesn't trip the bug.
- On client:
  - Use Minecraft 1.20.2
  - Install Fabric API; the vanilla client seems unaffected
- Start the server with the given mod set
- Join the server

### Expected Behavior

As a vanilla client would do; join perfectly fine

### Additional Server Info

No proxies were used; same computer and directly connected via `[::]` on Linux (equivalent to `[::1]`)

### Checklist

- [X] I have checked if this is specific to ViaFabric platform, and doesn't happen when running it on other platforms (Paper/Sponge/Velocity/Waterfall).
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Ampflower** [comment]
As Kichura has asked for; the packet, if you just want to outright disable it, is `fabric:registry/sync/direct` via CustomPayloadS2CPacket (extracted via Gadget), which appears to be during the configuration/pre-play phase.

I'd recommend seeing if it's possible to omit the individual version-specific entries if possible in the very unlikely case of someone trying to do multiversion with an actual modpack; tho realistically that's likely more fit for ViaFabricPlus than it is here.

**Comment by Kichura** [comment]
Update on this: 

Polymer somehow works again on 1.19.1, 1.19.2, 1.19.4, 1.20/1.20.1 and 1.20.3/1.20.4 again including 1.20.5/1.20.6 but not 1.19.3 and 1.20.2 - meaning progress is somehow being made.

**Comment by Kichura** [comment]
Update 2: We got the thing working at last with a silly workaround whilst all of this time, it felt like i was doing a quest.
![a](https://github.com/ViaVersion/ViaFabric/assets/68134602/4b30dcb9-2a2e-4e87-8a11-90e785587f73)

**Comment by Kichura** [comment]
The setting has been merged meaning this is now resolved, to use the feature - Open up the ViaFabric config and set `ignore-registry-sync-errors` to true.

**Comment by ArkoSammy12** [comment]
> The setting has been merged meaning this is now resolved, to use the feature - Open up the ViaFabric config and set `ignore-registry-sync-errors` to true.

Im glad to see this issue being resolved after 4 months of my original issue report on Polysit's repo, thank you.

One last thing. Are there any downsides to enabling `ignore-registry-sync-errors` that I should be aware of?

**Comment by FlorianMichael** [comment]
It basically disables Fabric's validation of registries, doing so may cause unexpected issues which would have gotten a proper error message before, but other than that you should be fine. Sorry for the wait.

**Comment by ArkoSammy12** [comment]
> It basically disables Fabric's validation of registries, doing so may cause unexpected issues which would have gotten a proper error message before, but other than that you should be fine. Sorry for the wait.

No worries, and thank you for the answer 👍
