### ISSUE TITLE
Fabric 1.20.5 Crash On Startup

### ISSUE THREAD

**Issue by GrimPlayzs** [ViaVersion/ViaFabric#322]
### `/viaversion dump` Output

Crash On Startup

### Console Error

```
https://mclo.gs/4qpkYGS
```

### Bug Description

The game crashes on startup with ViaFabric installed.

### Steps to Reproduce

1. Install Minecraft 1.20.5
2. Install Fabric
3. Install Fabric API
4. Install ViaFabric
5. Run Minecraft

### Expected Behavior

The game to run normally. 

### Checklist

- [ ] I have checked if this is specific to ViaFabric platform, and doesn't happen when running it on other platforms (Paper/Sponge/Velocity/Waterfall).
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Kichura** [comment]
Update ViaFabric jar, if it still causes issues then make a reply here.
