### ISSUE TITLE
server closing issue

### ISSUE THREAD

**Issue by ahshqhir** [ViaVersion/ViaFabric#327]
### `/viaversion dump` Output

None

### Bug Description

using it's latest snapshot prevents fabric server from closeing

### Steps to Reproduce

1.create 1.20.6 fabric server
2.install latest viaversion viabackward and viarewind mods
3.run server
4.run /stop

### Expected Behavior

server closing normally

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.
- [X] I have looked at https://www.spigotmc.org/resources/viarewind-legacy-support.52924/ and it does not offer a fix for my problem

**Comment by FlorianMichael** [comment]
Can you install this ViaFabric build and see if the issue still exists:
https://github.com/ViaVersion/ViaFabric/actions/runs/9024654485/artifacts/1489442198
