### ISSUE TITLE
Server Error: Incompatability with Via* 5.0.0 [ALPHA]

### ISSUE THREAD

**Issue by FeineKatze** [ViaVersion/ViaFabric#331]
### `/viaversion dump` Output

I can't provide one, server won't start

### Console Error

https://mclo.gs/24riXjB

### Bug Description

Server won't start with newest ViaFabric and newest ViaVersion / ViaBackwards (+FabricAPI)

### Steps to Reproduce

Create Server with newest versions of ViaFabric, ViaVersion and ViaBackwards (+FabricAPI)

### Expected Behavior

Server should start with all mods enabled and working

### Additional Server Info

Local Server with newest Fabric, ViaFabric works with ViaVersion v4.10.3 [Snapshot] / ViaBackwards v4.10.3 [Snapshot]

### Checklist

- [ ] I have checked if this is specific to ViaFabric platform, and doesn't happen when running it on other platforms (Paper/Sponge/Velocity/Waterfall).
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by FlorianMichael** [comment]
You can downloading working ViaFabric for ViaVersion 5 on the dev branch:
https://github.com/ViaVersion/ViaFabric/actions/runs/9087219528

It will be published on both modrinth and curseforge once the update is finished.
