### ISSUE TITLE
Server won't start with ViaFabric installed

### ISSUE THREAD

**Issue by imagelesskink** [ViaVersion/ViaFabric#338]
### `/viaversion dump` Output

Server won't start so I can't dump

### Console Error

         - Mod 'ViaFabric for 1.14' (viafabric-mc1144) 0.4.14+66-main requires version 1.14.4 of 'Minecraft' (minecraft), but only the wrong version is present: 1.20.4!
         - Mod 'ViaFabric for 1.15' (viafabric-mc1152) 0.4.14+66-main requires version 1.15.2 of 'Minecraft' (minecraft), but only the wrong version is present: 1.20.4!
         - Mod 'ViaFabric for 1.16' (viafabric-mc1165) 0.4.14+66-main requires version 1.16.5 of 'Minecraft' (minecraft), but only the wrong version is present: 1.20.4!
         - Mod 'ViaFabric for 1.17' (viafabric-mc1171) 0.4.14+66-main requires version 1.17.1 of 'Minecraft' (minecraft), but only the wrong version is present: 1.20.4!
         - Mod 'ViaFabric for 1.18' (viafabric-mc1182) 0.4.14+66-main requires version 1.18.2 of 'Minecraft' (minecraft), but only the wrong version is present: 1.20.4!
         - Mod 'ViaFabric for 1.19' (viafabric-mc1194) 0.4.14+66-main requires version 1.19.4 of 'Minecraft' (minecraft), but only the wrong version is present: 1.20.4!
         - Mod 'ViaFabric for 1.20.1' (viafabric-mc1201) 0.4.14+66-main requires version 1.20.1 of 'Minecraft' (minecraft), but only the wrong version is present: 1.20.4!
         - Mod 'ViaFabric for 1.20.5' (viafabric-mc1205) 0.4.14+66-main requires version 1.20.5-rc.2 of 'Minecraft' (minecraft), but only the wrong version is present: 1.20.4!

### Bug Description

Server refuses to start and tells me to install every version of minecraft

### Steps to Reproduce

1. Add ViaFabric
2. Start server

### Expected Behavior

Server starts

### Additional Server Info

I use a number of other mods. I can't run the latest version of Geyser without ViaFabric.

### Checklist

- [X] I have checked if this is specific to ViaFabric platform, and doesn't happen when running it on other platforms (Paper/Sponge/Velocity/Waterfall).
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Kichura** [comment]
Your viafabric copy is outdated.

**Comment by imagelesskink** [comment]
Well it's the latest version on Curseforge. What version should I be using, then?

**Comment by FlorianMichael** [comment]
CurseForge tends to not let releases through for quite a long time, use either GH action builds or the latest release from modrinth: https://modrinth.com/mod/viafabric/versions

**Comment by imagelesskink** [comment]
Installed from Modrinth and the same problem occurred.
`         - Mod 'ViaFabric for 1.14' (viafabric-mc1144) 0.4.14+71-dev requires version 1.14.4 of 'Minecraft' (minecraft), but only the wrong version is present: 1.20.4!
         - Mod 'ViaFabric for 1.15' (viafabric-mc1152) 0.4.14+71-dev requires version 1.15.2 of 'Minecraft' (minecraft), but only the wrong version is present: 1.20.4!
         - Mod 'ViaFabric for 1.16' (viafabric-mc1165) 0.4.14+71-dev requires version 1.16.5 of 'Minecraft' (minecraft), but only the wrong version is present: 1.20.4!
         - Mod 'ViaFabric for 1.17' (viafabric-mc1171) 0.4.14+71-dev requires version 1.17.1 of 'Minecraft' (minecraft), but only the wrong version is present: 1.20.4!
         - Mod 'ViaFabric for 1.18' (viafabric-mc1182) 0.4.14+71-dev requires version 1.18.2 of 'Minecraft' (minecraft), but only the wrong version is present: 1.20.4!
         - Mod 'ViaFabric for 1.19' (viafabric-mc1194) 0.4.14+71-dev requires version 1.19.4 of 'Minecraft' (minecraft), but only the wrong version is present: 1.20.4!
         - Mod 'ViaFabric for 1.20.1' (viafabric-mc1201) 0.4.14+71-dev requires version 1.20.1 of 'Minecraft' (minecraft), but only the wrong version is present: 1.20.4!
         - Mod 'ViaFabric for 1.20.5/6' (viafabric-mc1206) 0.4.14+71-dev requires version 1.20.5 or version 1.20.6 of 'Minecraft' (minecraft), but only the wrong version is present: 1.20.4!`

**Comment by Kichura** [comment]
You did not send the full error. Also the other viafabric jars are meant to be auto-picked based on what version you have. *(it picked mc1204 for you)*
