### ISSUE TITLE
Client-side per server version setting

### ISSUE THREAD

**Issue by creeper123123321** [ViaVersion/ViaFabric#34]

**Comment by creeper123123321** [comment]
Idea for implementing it: using a format like mc.example.com@1.12.2 (stolen idea from https://www.curseforge.com/minecraft/mc-mods/minerparty)

**Comment by Username404-59** [comment]
I like to see this happen ^^ (did a feature request months ago about that;  #20 ; but nobody answered it)

**Comment by creeper123123321** [comment]
Implemented
