### ISSUE TITLE
1.21 Support - ViaFabric

### ISSUE THREAD

**Issue by fluid46** [ViaVersion/ViaFabric#343]
### `/viaversion dump` Output

N/A

### Console Error

```
[https://mclo.gs/9G11cgC#L195]
```

### Bug Description

Not much more else to say, throwing exception: `java.lang.IllegalArgumentException: displayleaks <level> is not a valid sub-command name.` - I'm not too experienced with this jargon so thought I could leave it to someone who knows what they're doing.

### Steps to Reproduce

1. Put on your best robber outfit.
2. Go to actions
3. Whilst dodging the lasers click download build artifacts
4. Load the .jar file in as a server-side mod
5. Error detected?!?!

### Expected Behavior

The mod works.

### Additional Server Info

Using fabric 1.21 version 0.15.11, OpenJDK 21, modlist: 
![image](https://github.com/ViaVersion/ViaFabric/assets/45816552/bf145630-0f29-4cfb-a2b1-5ab80003045c)

### Checklist

- [X] I have checked if this is specific to ViaFabric platform, and doesn't happen when running it on other platforms (Paper/Sponge/Velocity/Waterfall).
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by FlorianMichael** [comment]
Outdated ViaVersion

**Comment by fluid46** [comment]
> Outdated ViaVersion

Can you recompile the 1.21 build with the correct version?

**Comment by FlorianMichael** [comment]
Unless you are sponsoring kenny, you won't be able to use it at all. You need to wait for the public release of ViaVersion/ViaBackwards

**Comment by fluid46** [comment]
Ah, I assume you're also waiting for that push.

Many thanks
