### ISSUE TITLE
Unable to connect to 1.20.1 server with 1.21 client (`update/1.21` branch)

### ISSUE THREAD

**Issue by helpimnotdrowning** [ViaVersion/ViaFabric#344]
### `/viaversion dump` Output

The command did not produce any output.

### Console Error

```
https://mclo.gs/V9DL72U
```

### Bug Description

I'm unable to connect to my 1.20.1 Purpur server with a locally-built clone of `update/1.21`, using only the jar that appears in `build/libs` (builds as `ViaFabric-0.4.14+null-1.21.jar`).

### Steps to Reproduce

1. Build new JAR of branch `update/1.21` (not using latest Actions build, has broken command preventing startup)
2. Include newly built `build/libs/ViaFabric-0.4.14+null-1.21.jar` into mods/ directory
3. Start game, version can be set to either "AUTO" or "1.20.1"
4. Try to connect to (Purpur?) 1.20.1 server
5. Observe either in-game message saying "Outdated server! I'm still on 1.20.1" or (less likely) error "java.net.SocketException: Connection reset" (see mclo.gs log)

### Expected Behavior

Successful (more or less, since the branch may/may not be ready) connection to server

### Additional Server Info

Client: 
|||
|--|--|
|Minecraft|1.21|
|Fabric Loader|0.15.11|
|Fabric API|0.100.1+1.21|
|ViaFabric|0.4.14+null-1.21, client-side mode both enabled and disabled|
|(includes) ViaVerision|`viaversion-5.0.0-SNAPSHOT-downgraded-1.8-shaded-1.8.jar`|

Server:
|||
|--|--|
|Minecraft|1.20.1|
|Purpur|git-Purpur-2062 (MC: 1.20.1)|

### Checklist

- [ ] I have checked if this is specific to ViaFabric platform, and doesn't happen when running it on other platforms (Paper/Sponge/Velocity/Waterfall).
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by FlorianMichael** [comment]
You can't use this branch without preview ViaVersion/ViaBackwards
