### ISSUE TITLE
Incompatibility of ReplayMod and ViaFabric mods

### ISSUE THREAD

**Issue by Timokaproka** [ViaVersion/ViaFabric#346]
### `/viaversion dump` Output

https://dump.viaversion.com/a493affa2d2393d4fe88d09d1e4dc94d94ae0a06fb6d977f4f46d69f956fd66e

### Console Error

```
https://mclo.gs/Y7BrTcn
```

### Bug Description

Returns an error: "io.netty.handler.codec.DecoderException: com.viaversion.viaversion.exception.InformativeException: Please report this on the Via support Discord or open an issue on the relevant GitHub repository
Source 0: com.viaversion.viaversion.rewriter.CommandRewriter$$Lambda/0x0000020d01c29b20"
![Безымянный](https://github.com/ViaVersion/ViaFabric/assets/80510345/f093dd31-dd69-4ef3-a802-5608cc84397c)

### Steps to Reproduce

1) Install replaymod (2.6.15)
2) Install ViaFabric  (0.4.14+73-main)
3) Enable client mode
4) Try logging into the server version 1.20.1

### Expected Behavior

It was expected that the mod would be compatible with replaymod and the connection to the server would be without problems

### Additional Server Info

The server has a Purpur core. ViaVersion is not installed on the server. Client mode is enabled.
Installed Mods: 
1) fabric-api-0.97.1+1.20.4
2) replaymod-1.20.4-2.6.15
3) ViaFabric-0.4.14+73-main

### Checklist

- [ ] I have checked if this is specific to ViaFabric platform, and doesn't happen when running it on other platforms (Paper/Sponge/Velocity/Waterfall).
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by FlorianMichael** [comment]
See https://github.com/ReplayMod/ReplayMod/issues/972

**Comment by Timokaproka** [comment]
> See [ReplayMod/ReplayMod#972](https://github.com/ReplayMod/ReplayMod/issues/972)

It looks like you didn't understand my problem. My game runs fine, but they don't let me log in to the SERVER. By the way, when using ViaFabricPlus with replaymod, it is not observed.

**Comment by FlorianMichael** [comment]
I do understand your issue and I know it's caused by ReplayMod, there are various issues caused by it which should be all covered with our report to ReplayMod

**Comment by Timokaproka** [comment]
> I do understand your issue and I know it's caused by ReplayMod, there are various issues caused by it which should be all covered with our report to ReplayMod

But there is no problem when using ViaFabricPlus. Isn't this a problem specifically on the part of ViaFabric?

**Comment by FlorianMichael** [comment]
We don't have any ReplayMod integration in ViaFabric, so no.
