### ISSUE TITLE
ViaFabric 与 Replay Mod 一起安装时无法正常运行

### ISSUE THREAD

**Issue by xingchen-Forever** [ViaVersion/ViaFabric#348]
### `/viaversion dump` Output

很抱歉，由于我无法进入包含聊天框的界面，所以无法运行此命令，并且在单人模式下不会出现此问题

### Bug Description

<img width="437" alt="Snipaste_2024-06-30_19-29-09" src="https://github.com/ViaVersion/ViaFabric/assets/76945134/de1f14d2-7c84-433c-a776-deeab31cea6a">

### Steps to Reproduce

使用1.20.1fabric客户端，Fabric loader 版本：0.15.11，fabric api版本：0.91.1
同时安装mod：[录像回放] replaymod-1.20.1-2.6.13和[跨版本] ViaFabric-0.4.14+66-main
此时尝试跨版本加入服务器，则显示上图的断开消息

### Expected Behavior

在有Replay Mod 的情况下，viafabric仍正常工作，可以转换版本协议并加入服务器

### Additional Server Info

我使用1.20.1fabric客户端

### Checklist

- [X] I have checked if this is specific to ViaFabric platform, and doesn't happen when running it on other platforms (Paper/Sponge/Velocity/Waterfall).
- [ ] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Kichura** [comment]
这是[ReplayMod's #972](https://github.com/ReplayMod/ReplayMod/issues/972) 的重复。
