### ISSUE TITLE
1.8.9 Not loading

### ISSUE THREAD

**Issue by Qubarium** [ViaVersion/ViaFabric#349]
### `/viaversion dump` Output

I can't go to Minecraft and run a command

### Console Error

https://mclo.gs/3FqjmkA

### Bug Description

Prevents minecraft from starting

### Steps to Reproduce

1 Run

### Expected Behavior

Minecraft 1.8.9

### Checklist

- [ ] I have checked if this is specific to ViaFabric platform, and doesn't happen when running it on other platforms (Paper/Sponge/Velocity/Waterfall).
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Kichura** [comment]
Confirmed bug, Seems to be caused by a broken class called from viafabric's init system.

**Comment by creeper123123321** [comment]
fixed in a5d5adb
