### ISSUE TITLE
Add blue ping when Via is active

### ISSUE THREAD

**Issue by creeper123123321** [ViaVersion/ViaFabric#35]
TODO: accessibility (daltonism and narrator)

**Comment by creeper123123321** [comment]
This could interact with send-supported-versions on server

**Comment by creeper123123321** [comment]
todo: backport

**Comment by Kichura** [comment]
Update for this one: Since 1.20.2 converted GUI textures into sprites, the blue ping system needs to be changed to support it. *(The VIA icon already has been done)*
