### ISSUE TITLE
"Stepping" is not reverted in 1.8.9 (and likely all versions before that too)

### ISSUE THREAD

**Issue by Yndranth** [ViaVersion/ViaFabric#350]
Stepping is a feature that lets you go up blocks, however it is notoriously broken in literally every version of Minecraft.
This is also the reason blip ups happen which was mentioned in a different issue. Reverting stepping would make blip ups re appear along side all other stepping glitches. This wiki page explains how stepping works https://www.mcpk.wiki/wiki/Stepping however it likely doesn't mention everything stepping related. 
Blip ups which were already mentioned also have a wiki page https://www.mcpk.wiki/wiki/Blip https://www.youtube.com/watch?v=BjNbUP5-4wo however there are MANY other types of blips, you can blip on a block and get up when falling for a certain height, you can blip against a wall and a ceiling, and also blip on steppable blocks aka a blip up. Blip ups happen due to you landing on air allowing you to jump a tick earlier than you're meant to.
The last main glitch stepping causes is jump cancelling aka grinding https://www.mcpk.wiki/wiki/Jump_Cancel you can jump cancel on stairs (tho this is still a thing in all new version of mc), and on ceiling which was fixed in 1.14.

**Comment by Kichura** [comment]
Not possible to fix in ViaVersion's internal code as this requires a whole override in the movement code how to differences with the game versions.
