### ISSUE TITLE
1.8.9 and below corner panes have an incorrect hitbox

### ISSUE THREAD

**Issue by Yndranth** [ViaVersion/ViaFabric#351]
![Screenshot_20240703_235026](https://github.com/ViaVersion/ViaFabric/assets/154561084/27c73606-8359-4949-bdd0-59c6f9db49f1)
![Screenshot_20240703_235324](https://github.com/ViaVersion/ViaFabric/assets/154561084/024d1b3e-a9dd-40b5-b646-c5a55306efbc)

Even tho hitboxes of panes have been changed the corner 3 panes is missing a column of pixels. Panes that are connected to walls or against another pane are a pixel smaller than they might seem to be (which was fixed in 1.9) and correctly reimplemented, HOWEVER because of this a corner of 2 such panes causes a missing column which has not been reimplemented

**Comment by Kichura** [comment]
Similar answer *(which is the VFP part)* from #352 applies here.
