### ISSUE TITLE
Chest and anvil manipulation

### ISSUE THREAD

**Issue by Yndranth** [ViaVersion/ViaFabric#352]
Chests and anvils can be manipulated as they dont have a fixed collision hitbox. Standing against an anvil and looking a different anvil thats rotated will cause the hitbox of the anvil ur against to change to the one ur looking at clipping your hitbox inside the anvil. Same thing happens with chests. https://www.mcpk.wiki/wiki/Anvil/Chest_Manipulation

**Comment by Kichura** [comment]
1. The fixes have been implemented in [ViaFabricPlus](https://github.com/ViaVersion/ViaFabricPlus) instead as ViaFabric can't fix these ones.
2. Also not possible to do as it's a collision box change and only works in singleplayer.
