### ISSUE TITLE
not joining to server

### ISSUE THREAD

**Issue by MahadRegent** [ViaVersion/ViaFabric#354]
### `/viaversion dump` Output

https://dump.viaversion.com/76cffa9cf27d47955f7f1a4dc443a0ccddeec8072ef02a7976356e57a068d1e5

### Console Error

I dont have access to the console, i just tryed to join a server and have a error

### Bug Description

![Снимок экрана_20240706_234800](https://github.com/ViaVersion/ViaFabric/assets/128891974/5a90471c-5c7a-41d9-bf1f-79735c584b76)

### Steps to Reproduce

1. Tested all version which can i join to the server. error on scrinshoot no changes - minecraft version 1.21

### Expected Behavior

> io.netty.handler.codec.DecoderException: com.viaversion.viaversion.exception.InformativeException: Please report this on the Via support Discord or open an issue on the relevant GitHub repository
> Packet Type: LEVEL_CHUNK_WITH_LIGHT, Type: ChunkType1_18, Index: 1, Data: [], Source 0: com.viaversion.viaversion.protocols.v1_20to1_20_2.rewriter.BlockItemPacketRewriter1_20_2$$Lambda/0x0000000800dca018, Packet ID: 37
>       at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:98) ~[liquidbounce.jar:?]
>       at net.raphimc.vialoader.netty.ViaDecoder.channelRead(ViaDecoder.java:56) ~[net_raphimc_vialoader-3.0.1-f68f314315a44e76.jar:?]
>       at de.florianmichael.viafabricplus.protocoltranslator.netty.ViaFabricPlusViaDecoder.channelRead(ViaFabricPlusViaDecoder.java:42) ~[ViaFabricPlus-3.4.1.jar:?]
>       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[netty-transport-4.1.97.Final.jar:?]
>       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[netty-transport-4.1.97.Final.jar:?]
>       at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[netty-transport-4.1.97.Final.jar:?]
>       at io.netty.handler.flow.FlowControlHandler.dequeue(FlowControlHandler.java:202) ~[netty-handler-4.1.97.Final.jar:?]
>       at io.netty.handler.flow.FlowControlHandler.channelRead(FlowControlHandler.java:164) ~[netty-handler-4.1.97.Final.jar:?]
>       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442) ~[netty-transport-4.1.97.Final.jar:?]
>       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[netty-transport-4.1.97.Final.jar:?]
>       at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[netty-transport-4.1.97.Final.jar:?]
>       at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346) ~[liquidbounce.jar:?]
>       at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:318) ~[liquidbounce.jar:?]
>       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[netty-transport-4.1.97.Final.jar:?]
>       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[netty-transport-4.1.97.Final.jar:?]
>       at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[netty-transport-4.1.97.Final.jar:?]
>       at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346) ~[liquidbounce.jar:?]
>       at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:333) ~[liquidbounce.jar:?]
>       at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:455) ~[liquidbounce.jar:?]
>       at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:290) ~[liquidbounce.jar:?]
>       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[netty-transport-4.1.97.Final.jar:?]
>       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[netty-transport-4.1.97.Final.jar:?]
>       at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[netty-transport-4.1.97.Final.jar:?]
>       at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286) ~[netty-handler-4.1.97.Final.jar:?]
>       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442) ~[netty-transport-4.1.97.Final.jar:?]
>       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[netty-transport-4.1.97.Final.jar:?]
>       at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[netty-transport-4.1.97.Final.jar:?]
>       at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) ~[netty-transport-4.1.97.Final.jar:?]
>       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440) ~[netty-transport-4.1.97.Final.jar:?]
>       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[netty-transport-4.1.97.Final.jar:?]
>       at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) ~[netty-transport-4.1.97.Final.jar:?]
>       at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:800) ~[netty-transport-classes-epoll-4.1.97.Final.jar:?]
>       at io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe$1.run(AbstractEpollChannel.java:425) ~[netty-transport-classes-epoll-4.1.97.Final.jar:?]
>       at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174) ~[netty-common-4.1.97.Final.jar:?]
>       at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167) ~[netty-common-4.1.97.Final.jar:?]
>       at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470) ~[netty-common-4.1.97.Final.jar:?]
>       at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:413) ~[netty-transport-classes-epoll-4.1.97.Final.jar:?]
>       at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[netty-common-4.1.97.Final.jar:?]
>       at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.97.Final.jar:?]
>       at java.base/java.lang.Thread.run(Thread.java:1583) [?:?]
> Caused by: com.viaversion.viaversion.exception.InformativeException: Please report this on the Via support Discord or open an issue on the relevant GitHub repository
> Packet Type: LEVEL_CHUNK_WITH_LIGHT, Type: ChunkType1_18, Index: 1, Data: [], Source 0: com.viaversion.viaversion.protocols.v1_20to1_20_2.rewriter.BlockItemPacketRewriter1_20_2$$Lambda/0x0000000800dca018, Packet ID: 37
> Caused by: java.lang.IndexOutOfBoundsException: readerIndex(19674) + length(8) exceeds writerIndex(19681): PooledUnsafeDirectByteBuf(ridx: 19674, widx: 19681, cap: 19681)
>       at io.netty.buffer.AbstractByteBuf.checkReadableBytes0(AbstractByteBuf.java:1442) ~[netty-buffer-4.1.97.Final.jar:?]
>       at io.netty.buffer.AbstractByteBuf.readLong(AbstractByteBuf.java:835) ~[netty-buffer-4.1.97.Final.jar:?]
>       at com.viaversion.viaversion.api.type.types.LongArrayType.read(LongArrayType.java:40) ~[com_viaversion_viaversion-common-5.0.1-8bc85a28e9a85911.jar:?]
>       at com.viaversion.viaversion.api.type.types.LongArrayType.read(LongArrayType.java:29) ~[com_viaversion_viaversion-common-5.0.1-8bc85a28e9a85911.jar:?]
>       at com.viaversion.viaversion.api.type.types.chunk.PaletteType1_18.read(PaletteType1_18.java:52) ~[com_viaversion_viaversion-common-5.0.1-8bc85a28e9a85911.jar:?]
>       at com.viaversion.viaversion.api.type.types.chunk.ChunkSectionType1_18.read(ChunkSectionType1_18.java:47) ~[com_viaversion_viaversion-common-5.0.1-8bc85a28e9a85911.jar:?]
>       at com.viaversion.viaversion.api.type.types.chunk.ChunkType1_18.read(ChunkType1_18.java:59) ~[com_viaversion_viaversion-common-5.0.1-8bc85a28e9a85911.jar:?]
>       at com.viaversion.viaversion.api.type.types.chunk.ChunkType1_18.read(ChunkType1_18.java:37) ~[com_viaversion_viaversion-common-5.0.1-8bc85a28e9a85911.jar:?]
>       at com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.read(PacketWrapperImpl.java:140) ~[com_viaversion_viaversion-common-5.0.1-8bc85a28e9a85911.jar:?]
>       at com.viaversion.viaversion.protocols.v1_20to1_20_2.rewriter.BlockItemPacketRewriter1_20_2.lambda$registerPackets$4(BlockItemPacketRewriter1_20_2.java:97) ~[com_viaversion_viaversion-common-5.0.1-8bc85a28e9a85911.jar:?]
>       at com.viaversion.viaversion.api.protocol.AbstractProtocol.transform(AbstractProtocol.java:405) ~[com_viaversion_viaversion-common-5.0.1-8bc85a28e9a85911.jar:?]
>       at com.viaversion.viaversion.protocols.v1_20to1_20_2.Protocol1_20To1_20_2.transform(Protocol1_20To1_20_2.java:235) ~[com_viaversion_viaversion-common-5.0.1-8bc85a28e9a85911.jar:?]
>       at com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.apply(PacketWrapperImpl.java:369) ~[com_viaversion_viaversion-common-5.0.1-8bc85a28e9a85911.jar:?]
>       at com.viaversion.viaversion.protocol.ProtocolPipelineImpl.transform(ProtocolPipelineImpl.java:122) ~[com_viaversion_viaversion-common-5.0.1-8bc85a28e9a85911.jar:?]
>       at com.viaversion.viaversion.connection.UserConnectionImpl.transform(UserConnectionImpl.java:337) ~[com_viaversion_viaversion-common-5.0.1-8bc85a28e9a85911.jar:?]
>       at com.viaversion.viaversion.connection.UserConnectionImpl.transformClientbound(UserConnectionImpl.java:313) ~[com_viaversion_viaversion-common-5.0.1-8bc85a28e9a85911.jar:?]
>       at com.viaversion.viaversion.api.connection.UserConnection.transformIncoming(UserConnection.java:246) ~[com_viaversion_viaversion-common-5.0.1-8bc85a28e9a85911.jar:?]
>       at net.raphimc.vialoader.netty.ViaDecoder.decode(ViaDecoder.java:45) ~[net_raphimc_vialoader-3.0.1-f68f314315a44e76.jar:?]
>       at net.raphimc.vialoader.netty.ViaDecoder.decode(ViaDecoder.java:30) ~[net_raphimc_vialoader-3.0.1-f68f314315a44e76.jar:?]
>       at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:88) ~[liquidbounce.jar:?]
>       ... 39 more
> [23:50:00] [Render thread/INFO]: Successfully saved config 'modules'.
> [23:50:00] [Render thread/INFO]: Reloading integration browser JcefTab to Route(theme=net.ccbluex.liquidbounce.web.theme.Theme@45faa352, url=http://127.0.0.1:15000/default/#/)
> [23:50:00] [Render thread/WARN]: Not all defined tags for registry ResourceKey[minecraft:root / minecraft:block] are present in data pack: minecraft:fire_aspect_lightable
> [23:50:00] [Render thread/WARN]: Not all defined tags for registry ResourceKey[minecraft:root / minecraft:item] are present in data pack: minecraft:enchantable/mace
> [23:50:00] [Netty Epoll Client IO #14/ERROR]: Negative index in crash report handler (40/47)
> [23:50:00] [Netty Epoll Client IO #14/INFO]: MahadRegent9 SERVERBOUND PLAY: 0 (0x00) -> 0 (0x00) [1.21] PacketWrapper{type=null, id=0, values=[], readable=[]}
> [23:50:00] [Netty Epoll Client IO #14/ERROR]: An exception occurred while handling a packet
> io.netty.channel.StacklessClosedChannelException: null
>       at io.netty.channel.AbstractChannel$AbstractUnsafe.write(Object, ChannelPromise)(Unknown Source) ~[netty-transport-4.1.97.Final.jar:?]
> [23:50:00] [Netty Epoll Client IO #14/INFO]: MahadRegent9 SERVERBOUND PLAY: 27 (0x1B) -> 27 (0x1B) [1.21] PacketWrapper{type=null, id=27, values=[], readable=[]}
> [23:50:00] [Netty Epoll Client IO #14/ERROR]: An exception occurred while handling a packet
> io.netty.channel.StacklessClosedChannelException: null
>       at io.netty.channel.AbstractChannel$AbstractUnsafe.write(Object, ChannelPromise)(Unknown Source) ~[netty-transport-4.1.97.Final.jar:?]
> [0706/235000.698157:INFO:CONSOLE(76)] "[Router] Virtual screen change to disconnected", source: http://127.0.0.1:15000/default/assets/index-BjjrIT4-.js (76)
> [0706/235000.698238:INFO:CONSOLE(4)] "[WS] Cleaned up event listeners", source: http://127.0.0.1:15000/default/assets/index-BjjrIT4-.js (4)
> [0706/235000.698262:INFO:CONSOLE(76)] "[Router] Redirecting to disconnected", source: http://127.0.0.1:15000/default/assets/index-BjjrIT4-.js (76)
> [23:50:00] [Render thread/INFO]: Successfully saved config 'modules'.
> [23:50:00] [Render thread/INFO]: Reloading integration browser JcefTab to Route(theme=net.ccbluex.liquidbounce.web.theme.Theme@45faa352, url=http://127.0.0.1:15000/default/#/)
> [23:50:00] [Render thread/WARN]: Client disconnected with reason: Internal Exception: io.netty.handler.codec.DecoderException: com.viaversion.viaversion.exception.InformativeException: Please report this on the Via support Discord or open an issue on the relevant GitHub repository
> Packet Type: LEVEL_CHUNK_WITH_LIGHT, Type: ChunkType1_18, Index: 1, Data: [], Source 0: com.viaversion.viaversion.protocols.v1_20to1_20_2.rewriter.BlockItemPacketRewriter1_20_2$$Lambda/0x0000000800dca018, Packet ID: 37
> [0706/235000.964491:INFO:CONSOLE(4)] "Connecting to server at:  ws://127.0.0.1:15000", source: http://127.0.0.1:15000/default/assets/index-BjjrIT4-.js (4)
> [23:50:00] [epollEventLoopGroup-3-1/INFO]: [id: 0xfb550baf, L:/[0:0:0:0:0:0:0:0%0]:15000] READ: [id: 0xf425e297, L:/127.0.0.1:15000 - R:/127.0.0.1:53482]
> [23:50:00] [epollEventLoopGroup-3-1/INFO]: [id: 0xfb550baf, L:/[0:0:0:0:0:0:0:0%0]:15000] READ COMPLETE
> [0706/235001.005183:INFO:CONSOLE(4)] "[WS] Connected to server", source: http://127.0.0.1:15000/default/assets/index-BjjrIT4-.js (4)
> [0706/235001.012969:INFO:CONSOLE(4)] "[WS] Cleaned up event listeners", source: http://127.0.0.1:15000/default/assets/index-BjjrIT4-.js (4)
> [0706/235001.013081:INFO:CONSOLE(76)] "[Router] Redirecting to disconnected", source: http://127.0.0.1:15000/default/assets/index-BjjrIT4-.js (76)
> [0706/235001.086931:INFO:CONSOLE(4)] "Connecting to server at:  ws://127.0.0.1:15000", source: http://127.0.0.1:15000/default/assets/index-BjjrIT4-.js (4)
> [23:50:01] [epollEventLoopGroup-3-1/INFO]: [id: 0xfb550baf, L:/[0:0:0:0:0:0:0:0%0]:15000] READ: [id: 0x976dc00e, L:/127.0.0.1:15000 - R:/127.0.0.1:33596]
> [23:50:01] [epollEventLoopGroup-3-1/INFO]: [id: 0xfb550baf, L:/[0:0:0:0:0:0:0:0%0]:15000] READ COMPLETE
> [0706/235001.132285:INFO:CONSOLE(4)] "[WS] Connected to server", source: http://127.0.0.1:15000/default/assets/index-BjjrIT4-.js (4)
> [23:50:01] [epollEventLoopGroup-4-1/ERROR]: Error while processing request object: RequestObject(context=RequestContext(httpMethod=GET, uri=/api/v1/client/player, headers={Host=127.0.0.1:15000, Connection=keep-alive, sec-ch-ua="Not(A:Brand";v="24", "Chromium";v="122", sec-ch-ua-mobile=?0, User-Agent=Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/118.0.0.0 Safari/537.36, sec-ch-ua-platform="Linux", Accept=*/*, Accept-Language=ru-RU,ru;q=0.9,en-US;q=0.8,en;q=0.7, Sec-Fetch-Site=same-origin, Sec-Fetch-Mode=cors, Sec-Fetch-Dest=empty, Referer=http://127.0.0.1:15000/default/, Accept-Encoding=gzip, deflate, br}))
> java.lang.NullPointerException: null
>       at net.ccbluex.liquidbounce.web.socket.protocol.rest.game.PlayerRestKt.playerRest$lambda$0(PlayerRest.kt:172) ~[liquidbounce.jar:?]
>       at net.ccbluex.liquidbounce.web.socket.netty.HttpConductor.processRequestObject(HttpConductor.kt:60) ~[liquidbounce.jar:?]
>       at net.ccbluex.liquidbounce.web.socket.netty.HttpServerHandler.channelRead(HttpServerHandler.kt:101) ~[liquidbounce.jar:?]
>       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[netty-transport-4.1.97.Final.jar:?]
>       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[netty-transport-4.1.97.Final.jar:?]
>       at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[netty-transport-4.1.97.Final.jar:?]
>       at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:436) ~[netty-transport-4.1.97.Final.jar:?]
>       at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346) ~[liquidbounce.jar:?]
>       at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:318) ~[liquidbounce.jar:?]
>       at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:251) ~[netty-transport-4.1.97.Final.jar:?]
>       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442) ~[netty-transport-4.1.97.Final.jar:?]
>       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[netty-transport-4.1.97.Final.jar:?]
>       at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[netty-transport-4.1.97.Final.jar:?]
>       at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) ~[netty-transport-4.1.97.Final.jar:?]
>       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440) ~[netty-transport-4.1.97.Final.jar:?]
>       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[netty-transport-4.1.97.Final.jar:?]
>       at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) ~[netty-transport-4.1.97.Final.jar:?]
>       at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:800) ~[netty-transport-classes-epoll-4.1.97.Final.jar:?]
>       at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:509) ~[netty-transport-classes-epoll-4.1.97.Final.jar:?]
>       at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:407) ~[netty-transport-classes-epoll-4.1.97.Final.jar:?]
>       at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[netty-common-4.1.97.Final.jar:?]
>       at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.97.Final.jar:?]
>       at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-common-4.1.97.Final.jar:?]
>       at java.base/java.lang.Thread.run(Thread.java:1583) [?:?]
> [0706/235001.160339:INFO:CONSOLE(58)] "Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'identifier')", source: http://127.0.0.1:15000/default/assets/index-BjjrIT4-.js (58)
> [0706/235001.160405:INFO:CONSOLE(58)] "Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'identifier')", source: http://127.0.0.1:15000/default/assets/index-BjjrIT4-.js (58)

### Additional Server Info

mc.aresmine.ru version 1.19.4-1.20.4  and i use the latest build 3.4.1 viafabric

### Checklist

- [ ] I have checked if this is specific to ViaFabric platform, and doesn't happen when running it on other platforms (Paper/Sponge/Velocity/Waterfall).
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by MahadRegent** [comment]
---- Minecraft Network Protocol Error Report ----
// Too many suspicious packets

Time: 2024-06-29 21:30:18
Description: Packet handling error

io.netty.handler.codec.DecoderException: java.io.IOException: Packet play/clientbound/minecraft:take_item_entity (class_2775) was larger than I expected, found 16 bytes extra whilst reading packet clientbound/minecraft:take_item_entity
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:500)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:290)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	at io.netty.handler.flow.FlowControlHandler.dequeue(FlowControlHandler.java:202)
	at io.netty.handler.flow.FlowControlHandler.read(FlowControlHandler.java:139)
	at de.florianmichael.viafabricplus.protocoltranslator.netty.NoReadFlowControlHandler.read(NoReadFlowControlHandler.java:30)
	at io.netty.channel.AbstractChannelHandlerContext.invokeRead(AbstractChannelHandlerContext.java:837)
	at io.netty.channel.AbstractChannelHandlerContext.access$2000(AbstractChannelHandlerContext.java:61)
	at io.netty.channel.AbstractChannelHandlerContext$Tasks$2.run(AbstractChannelHandlerContext.java:1288)
	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:413)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: java.io.IOException: Packet play/clientbound/minecraft:take_item_entity (class_2775) was larger than I expected, found 16 bytes extra whilst reading packet clientbound/minecraft:take_item_entity
	at net.minecraft.class_2543.decode(class_2543.java:43)
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:530)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:469)
	... 17 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Netty Epoll Client IO #2
Stacktrace:
	at net.minecraft.class_2547.method_55622(class_2547.java:33)

-- Connection --
Details:
	Protocol: play
	Flow: CLIENTBOUND
	Server type: OTHER
	Server brand: LimboAPI (1.1.17) -> LimboFilter
Stacktrace:
	at net.minecraft.class_2547.method_55622(class_2547.java:33)
	at net.minecraft.class_2600.method_59803(class_2600.java:62)
	at net.minecraft.class_8673.method_60882(class_8673.java:136)
	at net.minecraft.class_8673.method_60881(class_8673.java:127)
	at net.minecraft.class_2535.exceptionCaught(class_2535.java:161)
	at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:346)
	at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:325)
	at io.netty.channel.AbstractChannelHandlerContext.fireExceptionCaught(AbstractChannelHandlerContext.java:317)
	at io.netty.channel.ChannelInboundHandlerAdapter.exceptionCaught(ChannelInboundHandlerAdapter.java:143)
	at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:346)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:447)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	at io.netty.handler.flow.FlowControlHandler.dequeue(FlowControlHandler.java:202)
	at io.netty.handler.flow.FlowControlHandler.read(FlowControlHandler.java:139)
	at de.florianmichael.viafabricplus.protocoltranslator.netty.NoReadFlowControlHandler.read(NoReadFlowControlHandler.java:30)
	at io.netty.channel.AbstractChannelHandlerContext.invokeRead(AbstractChannelHandlerContext.java:837)
	at io.netty.channel.AbstractChannelHandlerContext.access$2000(AbstractChannelHandlerContext.java:61)
	at io.netty.channel.AbstractChannelHandlerContext$Tasks$2.run(AbstractChannelHandlerContext.java:1288)
	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:413)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at java.base/java.lang.Thread.run(Thread.java:1583)

-- System Details --
Details:
	Minecraft Version: 1.21
	Minecraft Version ID: 1.21
	Operating System: Linux (amd64) version 6.9.3-3-MANJARO
	Java Version: 21.0.3, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 907323120 bytes (865 MiB) / 2147483648 bytes (2048 MiB) up to 4294967296 bytes (4096 MiB)
	CPUs: 12
	Processor Vendor: GenuineIntel
	Processor Name: 11th Gen Intel(R) Core(TM) i5-11400H @ 2.70GHz
	Identifier: Intel64 Family 6 Model 141 Stepping 1
	Microarchitecture: Tiger Lake
	Frequency (GHz): 2.70
	Number of physical packages: 1
	Number of physical CPUs: 6
	Number of logical CPUs: 12
	Graphics card #0 name: TigerLake-H GT1 [UHD Graphics]
	Graphics card #0 vendor: Intel Corporation (0x8086)
	Graphics card #0 VRAM (MiB): 256.00
	Graphics card #0 deviceId: 0x9a68
	Graphics card #0 versionInfo: unknown
	Graphics card #1 name: GA107M [GeForce RTX 3050 Mobile]
	Graphics card #1 vendor: NVIDIA Corporation (0x10de)
	Graphics card #1 VRAM (MiB): 4128.00
	Graphics card #1 deviceId: 0x25a5
	Graphics card #1 versionInfo: unknown
	Virtual memory max (MiB): 25172.80
	Virtual memory used (MiB): 11520.32
	Swap memory total (MiB): 17306.29
	Swap memory used (MiB): 1657.39
	Space in storage for jna.tmpdir (MiB): available: 857112.56, total: 920463.19
	Space in storage for org.lwjgl.system.SharedLibraryExtractPath (MiB): available: 857112.56, total: 920463.19
	Space in storage for io.netty.native.workdir (MiB): available: 857112.56, total: 920463.19
	Space in storage for java.io.tmpdir (MiB): available: 7796.59, total: 7866.50
	Space in storage for workdir (MiB): available: 857112.56, total: 920463.19
	JVM Flags: 12 total; -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M -XX:+DisableExplicitGC -XX:+AlwaysPreTouch -XX:+ParallelRefProcEnabled -Xms2048M -Xmx4096M -Xss2M

**Comment by Kichura** [comment]
This is the wrong repository to report this issue to as you are using ViaFabricPlus and not ViaFabric.

**Comment by FlorianMichael** [comment]
Your ViaFabricPlus version is also outdated.

**Comment by MahadRegent** [comment]
not changes with update && reported issue on viafabricplus (link - https://github.com/ViaVersion/ViaFabricPlus/issues/473)
