### ISSUE TITLE
[ViaFabric 1.21] Inventory related disconnection/crashes

### ISSUE THREAD

**Issue by ThatMG393** [ViaVersion/ViaFabric#355]
### `/viaversion dump` Output

https://dump.viaversion.com/c8c978cc4496b01c00516314df9e3aea698ef231c9345ef8fc7ed7453711e9e4

### Console Error

```
https://mclo.gs/lKbVbGg
```

### Bug Description

Inventory related disconnection (your game crashes instead when you have ViaFabric 0.14.4+main74 & ViaBackwards 
 5.0.2-SNAPSHOT installed instead of the server)

### Steps to Reproduce

1. Login to a MC 1.21 Server with a 1.20.4 (never tested on older clients)
2. Creative: just open your inventory.
    Survival: open your inventory and click an item.
3. Disconnected

> I also created an issue on the ViaVersion repo:
> https://github.com/ViaVersion/ViaVersion/issues/4012

### Expected Behavior

I don't get disconnected or my game will not crash.

### Additional Server Info

Minecraft Server Version: 1.21
Minecraft Client Version: 1.20.4
ViaFabric Version: 0.14.4+main74
ViaBackwards Version: 5.0.2-SNAPSHOT

### Checklist

- [ ] I have checked if this is specific to ViaFabric platform, and doesn't happen when running it on other platforms (Paper/Sponge/Velocity/Waterfall).
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Kichura** [comment]
Update ViaVersion.

**Comment by ThatMG393** [comment]
> Update ViaVersion.

How? Isn't ViaVersion already included in ViaFabric?

**Comment by Kichura** [comment]
> > Update ViaVersion.
> 
> ~How? Isn't ViaVersion already included in ViaFabric?~ Seems like recompiling this project fixed the problem.

It is bundled but the bundled version is outdated, meaning you have to install latest viaversion from CI into your mods folder as override.
