### ISSUE TITLE
Clientside ViaFabric Instandly crashing

### ISSUE THREAD

**Issue by UltraBlackLinux** [ViaVersion/ViaFabric#36]
**Describe the bug, provide any errors**
https://paste.ee/p/X67EA

**How can we reproduce it?**
1. Use mc 1.16'
2. Start Minecraft
3. Instand crash

**Expected behaviour**
Start...

**Comment by creeper123123321** [comment]
Downlod ViaVersion from https://ci.viaversion.com/job/ViaVersion/lastSuccessfulBuild/artifact/jar/target/ViaVersion-3.0.2-SNAPSHOT.jar

**Comment by UltraBlackLinux** [comment]
Wait, WHAT? I had it Installed, but I downloaded it from the link you gave me and it worked - oof. Thanks anyways.
