### ISSUE TITLE
Crash on 1.20.1

### ISSUE THREAD

**Issue by gi-b716** [ViaVersion/ViaFabric#361]
### `/viaversion dump` Output

Not applicable, as the game cannot be accessed

### Console Error

[crash log](https://mclo.gs/Mlhg8o2)

### Bug Description

I have tried various viaversions, and for some reason, only one version does not give such an error (ViaFabric 0.4.10+40-main). I have also tried Java17 and Java21, and neither works. I would like to know why, and I really want to update my viaversion.

### Steps to Reproduce

1. Log in using the [GSZYpack 1.20.1 client](https://modrinth.com/modpack/gpack/version/1.20.1-3.1.0) (I chose GSZYpack because it is a package based on my client's module and can simulate the effects of my client)
2. Switch to the latest viaversion version
3. Start the game

### Expected Behavior

The game launches normally.

### Checklist

- [X] I have checked if this is specific to ViaFabric platform, and doesn't happen when running it on other platforms (Paper/Sponge/Velocity/Waterfall).
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Kichura** [comment]
Can you test viafabric with just fabric api active? if it manages to fix itself then it's a third party mod preventing dependencies from loading correctly. *(otherwise, bad config)*

**Comment by gi-b716** [comment]
> 您能只在 fabric api 处于活动状态的情况下测试 viafabric 吗？如果它设法自行修复，那么它就是第三方模块，阻止依赖项正确加载。_（否则，配置错误）_

Let me try it

**Comment by gi-b716** [comment]
> Also replaymod 2.6.15 is not supported, please update it.

I tried updating the replay and it worked!
