### ISSUE TITLE
Could you make a never version of viafabric for 1.19.2 as fabric mod?

### ISSUE THREAD

**Issue by azzake** [ViaVersion/ViaFabric#367]
**Is your feature request related to a problem? Please describe.**
I wanted to ask if the developers of that plugin/mod could make a newer fabric mod version for Minecraft 1.19.2.
The current version of this mod is Via Fabric 0.4.9+21-main. I wanted to use a newer version of via backwards, but it requires a newer version of via version, and via version mod requires at least 0.4.10 version of via fabric mod. But this version is unavailable for 1.19.2.

(Optional)
Yes, it is

**Describe the solution you'd like**
An update of fabric mod for this version.

**Describe alternatives you've considered**
I didn't consider any alternative.

**Which versions is this for?**
1.19.2

**Comment by Kichura** [comment]
1.19.2 will not be updated as 1.19.4 has no issues running properly with existing mods out in the wild. The reason why 1.20.1 and 1.20.4 co-exist on the other hand is because of networking code changes that happened starting in 1.20.2, hence the addition of both.
