### ISSUE TITLE
Softlocking woth BUNCH of text on disconnect

### ISSUE THREAD

**Issue by lynrayy** [ViaVersion/ViaFabric#373]
### `/viaversion dump` Output

https://dump.viaversion.com/c33873ad7ed94a0eb892c1890fcb9fe80bab31f3ef7db57d5ddafbe4b564d9df

### Console Error

```
Put the mclo.gs link or text here.
```
https://gist.github.com/lynrayy/ffda911af4d8eea72d95e0eabd516090

### Bug Description

Sometimes i got disconnected with bunch of text without any possibiity to exit to menu
![image](https://github.com/user-attachments/assets/7599fa63-dfb7-4ff7-a568-b7c07cfc3a4c)

### Steps to Reproduce

IDK

### Expected Behavior

Can press "leave to server list" or press ESC to exit to servers list

### Checklist

- [X] I have checked if this is specific to ViaFabric platform, and doesn't happen when running it on other platforms (Paper/Sponge/Velocity/Waterfall).
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by lynrayy** [comment]
This server
`161.97.181.152:25565`

**Comment by FlorianMichael** [comment]
Please provide the full client log

**Comment by Kichura** [comment]
Your minecraft version is no longer supported, Update to 1.20.4 and also viafabric too.

**Comment by lynrayy** [comment]
What's the point of this mod even existing if I have to use the latest versions of the game?

**Comment by Kichura** [comment]
1.20.1 is also supported but 1.20.2 has been superseded in favor of 1.20.3/4 instead.
