### ISSUE TITLE
cant join 1.21.3 Lan world

### ISSUE THREAD

**Issue by randomstuff69** [ViaVersion/ViaFabric#382]
### `/viaversion dump` Output

https://dump.viaversion.com/f480524051c9ebda687b443d74f7230c0ac6d3094c4dc565c257fd6890783f99

### Console Error

```
Put the mclo.gs link or text here.
```

### Bug Description

cant join 1.21.3 Lan server on 1.20.4 with viafabric version 0.4.16 85-main from modrinth
![image](https://github.com/user-attachments/assets/c1eda6d9-c866-4027-8cd8-d3a05f5f45b1)

### Steps to Reproduce

1. login to a 1.21.3 Lan server on minecraft version 1.20.4 viafabric version 0.4.16 85-main 2. the error happens

### Expected Behavior

me joining the server without incompatible version error

### Additional Server Info

1.21.3 basic Lan server with NO mods

### Checklist

- [X] I have checked if this is specific to ViaFabric platform, and doesn't happen when running it on other platforms (Paper/Sponge/Velocity/Waterfall).
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by HowardZHY** [comment]
Your ViaFabric build is ouddated, and you need ViaBackwards to join newer versions.
https://modrinth.com/mod/viafabric/versions
https://modrinth.com/mod/viabackwards/versions
