### ISSUE TITLE
Kicked by Bungeecord error

### ISSUE THREAD

**Issue by UltraBlackLinux** [ViaVersion/ViaFabric#39]
**Describe the bug, provide any errors**
A clear and concise description of what the bug is. Can you https://hastebin.com the error?

**How can we reproduce it?**
1. Login on 1.8.x via 1.16.1'
2. join Neruxvace.net and Interact with the world by pressing RMB on a block
3.  ![Screenshot_20200730_165147](https://user-images.githubusercontent.com/62404294/88938054-2fa44700-d285-11ea-8cbf-f658e8edddaa.png)

**Expected behaviour**
nothing happens

**ViaVersion Dump:**
https://dump.viaversion.com/138651a609ba7a02a04108be620e0e3be2558ca76a484ea1ced1f6b8428eec65

**Additional server info**
BungeeCord

~~**Also sth I noticed**~~
~~On this server, I get 1 fps every 2 seconds when joining the Wollbattle Spiralmin map (also some others). I think its a viaversion problem.~~
Edit: Ignore the FPS thing, its seems to be a general minecraft problem

**Comment by KennyTV** [comment]
"de.exceptionflug.protocolize"

**Comment by UltraBlackLinux** [comment]
what?

**Comment by KennyTV** [comment]
We can't fix someone else's protocol injection.

**Comment by UltraBlackLinux** [comment]
oh ok.
