### ISSUE TITLE
older clients can't join 1.21.4

### ISSUE THREAD

**Issue by nightcrawcode** [ViaVersion/ViaFabric#396]
### `/viaversion dump` Output

https://dump.viaversion.com/f63d932facf1940548845ca67e8b30a44d146fa33a0a54ad294f2e457c1857a5

### Console Error

```
https://mclo.gs/WS81NF8
```

### Bug Description

When older clients connect to the server they are unable to due to the server sending a "network protocol error" however when clients with 1.21.4 connect. No errors are shown

### Steps to Reproduce

1. Open Minecraft client with version between version 1.8 - 1.21.3
2. Connect to server
3. The error shows up

### Expected Behavior

Clients should be able to connect without any issues

### Additional Server Info

Server uses no proxy. Runs on fabric with Minecraft 1.21.4, uses a lot of mods but ones that I think might be the issue is geyser, and blue map.

### Checklist

- [X] I have checked if this is specific to ViaFabric platform, and doesn't happen when running it on other platforms (Paper/Sponge/Velocity/Waterfall).
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Kichura** [comment]
Since you have mentioned "1.8", this will mean that it's a duplicate report of: https://github.com/ViaVersion/ViaBackwards/issues/642

However if 1.19.1 and up are also affected then please make a reply.

**Comment by nightcrawcode** [comment]
> However if 1.19.1 and up are also affected then please make a reply.

1.19.1 and newer clients are effective. (Except 1.21.4)

**Comment by Kichura** [comment]
Then please consider verifying the following:

1. Does viafabric and viabackwards recover when disabling all third party mods? (except fabric api ofc)
2. Have you updated viaversion and viabackwards to newest modrinth builds?
3. If first question is a yes, Then you have bad third party mod(s) active.

**Comment by nightcrawcode** [comment]
For the first one, no
The second, yes

**Comment by HowardZHY** [comment]
Try to remove Krypton, and you have many Datapacks that doesn't compatible with 1.21.4

**Comment by nightcrawcode** [comment]
Hey, it works now
It was that datapacks.

Thank you for the help!
