### ISSUE TITLE
1.21.1 isnt supported on viafabric but it is on viabackwards???

### ISSUE THREAD

**Issue by randomstuff69** [ViaVersion/ViaFabric#398]
**Is your feature request related to a problem? Please describe.**
so 1.21.1 is supported for viabackwards but not for viafabric but viabackwards needs viafabric to work

**Is this related specifically to ViaFabric?**

**Describe the solution you'd like**
add 1.21.1 to viafabric

**Describe alternatives you've considered**
none

**Which versions is this for?**
1.21.1

**Comment by Kichura** [comment]
Will not be done as 1.21.4 has superseded it including 1.21.3, but older builds of viafabric are available as a workaround but you will need to include latest viaversion jar.
