### ISSUE TITLE
Via version kicks when respawning

### ISSUE THREAD

**Issue by UltraBlackLinux** [ViaVersion/ViaFabric#40]
**Describe the bug, provide any errors**
A clear and concise description of what the bug is. Can you https://hastebin.com the error?

**How can we reproduce it?**
1. Login on any version'
2. die + respawn or join the server

**Expected behaviour**
respawn

**Log**
https://hastebin.com/gibuheceqa.php

**Screenshots**
![Screenshot_20200730_223242](https://user-images.githubusercontent.com/62404294/88971719-b45a8980-d2b4-11ea-820a-e271c92c4f79.png)

**ViaVersion Dump:**
other error

**Comment by KennyTV** [comment]
We need the full error from your logs.

**Comment by UltraBlackLinux** [comment]
https://hastebin.com/gibuheceqa.php

**Comment by KennyTV** [comment]
On what server was that?

**Comment by UltraBlackLinux** [comment]
lemoncloud.net

**Comment by Kichura** [comment]
since lemoncloud now uses a enforced respawning mechanic, this issue is considered fixed.
