### ISSUE TITLE
ViaFabric Crashes Minecraft on Start

### ISSUE THREAD

**Issue by kacperleague9** [ViaVersion/ViaFabric#44]
**Describe the bug, provide any errors**
A clear and concise description of what the bug is. Can you paste the error into https://gist.github.com?
https://gist.github.com/kacperleague9/353f9deed4379e58f619af74301474d2
**Is this happening specifically on ViaFabric?**
(Optional) yes only viafabric
- [ ] It seems to not happen when using ViaVersion/ViaBackwards/ViaRewind installed on Bukkit/BungeeCord/Sponge/Velocity server.

**How can we reproduce it?**
1. Add viafabric to mods.
2. Game will crash on start.

**Expected behaviour**
Game should start normally

**Additional server info**
[N/A]

**Comment by creeper123123321** [comment]
Crash report seems incomplete, can you post it?

**Comment by creeper123123321** [comment]
> net.fabricmc.loader.discovery.ModResolutionException: Could not find required mod: optifabric requires {minecraft @ [1.16.1]}
Looks like an OptiFabric issue

**Comment by creeper123123321** [comment]
Looks like a config file syntax error

**Comment by kacperleague9** [comment]
Hey, i ctrl + a all crash log!
Also fixed optifabric and it works correctly. Only crashes when viafabric is added.
I do not have any config files tho. Like i have only mod jars [idk why but configs dont generate]

**Comment by maximeurban** [comment]
what is the version of viafabric you're trying to play with ?

**Comment by kacperleague9** [comment]
Latest fabric fixed that issue for me
