### ISSUE TITLE
multiconnect is incompatible with .viafabric address

### ISSUE THREAD

**Issue by creeper123123321** [ViaVersion/ViaFabric#46]
**Describe the bug, provide any errors**
It shows unknown host when connecting

**Is this happening specifically on ViaFabric?**
(Optional)
- [x] It seems to not happen when using ViaVersion/ViaBackwards/ViaRewind installed on Bukkit/BungeeCord/Sponge/Velocity server.

**How can we reproduce it?**
Install ViaFabric + multiconnect and try to use .viafabric

**Expected behaviour**
Should work normally

**Screenshots**

**ViaVersion Dump:**
- Type /viaversion dump, and put the link here.

**Additional server info**
Is server using a proxy (eg. BungeeCord/Waterfall/Travertine/Velocity)? What software is it using and what plugins? Are you running on client-side mode? (Debug hud (F3) has server brand)

**Comment by Earthcomputer** [comment]
https://github.com/Earthcomputer/multiconnect/commit/84343e3830cedba544ce2c2457e4f23ef850769f

**Comment by creeper123123321** [comment]
> https://github.com/Earthcomputer/multiconnect/commit/84343e3830cedba544ce2c2457e4f23ef850769f

Wouldnt getHostName return the .viafabric address?

**Comment by creeper123123321** [comment]
You could use ClientConnection.connect(address... Instead of InetAddress.getName

**Comment by Earthcomputer** [comment]
What??

**Comment by Earthcomputer** [comment]
Oh, right, I see
