### ISSUE TITLE
Minecraft 1.16.2 crashes on startup.

### ISSUE THREAD

**Issue by mygizli04** [ViaVersion/ViaFabric#49]
**Describe the bug, provide any errors**
Minecraft 1.16.2 doesn't open at all with the latest fabric api ( 0.19.0+build.398 ) and viafabric ( 0.2.9-SNAPSHOT+build-435.1 ). On logs it always gets stuck in "Loading block connection mappings ..." but here's the [full logs](https://gist.github.com/mygizli04/66de8a959a9147928639c0c16e13c058) anyway.

**How can we reproduce it?**
1. Simply try opening minecraft with viafabric installed. It opens like normal if viafabric is uninstalled.

**Additional info**
No other mods or add-ons are installed. Just viafabric and fabric api, and fabric loader itself, of course.

**Comment by creeper123123321** [comment]
Couldn't reproduce.

**Comment by mygizli04** [comment]
I'm on macOS 10.15.4

**Comment by Earthcomputer** [comment]
This is an issue with programmer art injector, take it up with them

**Comment by mygizli04** [comment]
Fixed when i removed the programmer art injector from inside the jar.
