### ISSUE TITLE
Protocol Error while loading mappings

### ISSUE THREAD

**Issue by UltraBlackLinux** [ViaVersion/ViaFabric#58]
**Describe the bug, provide any errors**
Its just an error at game startup, and I find it ugly, so I report it finally. Doesnt seem to be something crucial.
https://gist.github.com/UltraBlackLinux/d3f154058cdc58da1daf790fafaef5de

**Is this happening specifically on ViaFabric?**
propably

**How can we reproduce it?**
start the game

**ViaVersion Dump:**
https://dump.viaversion.com/1c491b30f29885cf55a8f03f9cc10b52e7fc2a3a5d7686da4a352386e778ab8a

**Comment by KennyTV** [comment]
Your Via versions are mismatched. Use 3.2.0 with 3.2.0, or 3.1.1 with 3.1.1.

**Comment by UltraBlackLinux** [comment]
thanks! ;)
I knew there was a problem on my side!
