### ISSUE TITLE
ViaBackwards and ViaRewind on curseforge

### ISSUE THREAD

**Issue by creeper123123321** [ViaVersion/ViaFabric#59]
**Is your feature request related to a problem? Please describe.**
Can't install viabackwards and rewind on aternos

**Is this related specifically to ViaFabric?**
(Optional)
- [x] It seems to not apply for ViaVersion/ViaBackwards/ViaRewind installed on Bukkit/BungeeCord/Sponge/Velocity servers.

**Describe the solution you'd like**
Upload to curseforge

**Describe alternatives you've considered**
Bundle these mods in viafabric

**Which versions is this for?**
All versions

**Comment by Username404-59** [comment]
The alternative you mentionned seems more suitable for viafabric, but if you want the plugins on curseforge, go  make an issue on the [viaversion repository](https://github.com/ViaVersion/ViaVersion).

**Comment by creeper123123321** [comment]
Re-uploads: https://www.curseforge.com/minecraft/mc-mods/viabackwards/ https://www.curseforge.com/minecraft/mc-mods/viarewind
