### ISSUE TITLE
ViaFabric lagging

### ISSUE THREAD

**Issue by UltraBlackLinux** [ViaVersion/ViaFabric#61]
**Describe the bug, provide any errors**
Viafabric kind of acts like a ping spoofer: My ping is often balls; Blocks are bugging away and maps take pretty long to load. I also often get kicked for flying.
I sometimes got this weird error in the logs: https://gist.github.com/UltraBlackLinux/e7c58eac3a214fe5b24d9e74e9554549

**Is this happening specifically on ViaFabric?**
- [x] Yes

**How can we reproduce it?**
1. Login on 1.16.3
2. bedwarspractice.club
3. Blocksumo

**Expected behaviour**
No Lag/Bad Ping, Flawless gameplay

**ViaVersion Dump:**
https://dump.viaversion.com/34dc9bbd2b559b2e9f87de80ca7f0df81f86624fcdbd1eb0a35385a664ac9ff0

**Additional server info**
Spigot 1.8 + BungeeCord 1.16
Viaversion
Idk if more

**Comment by Kichura** [comment]
Can't seem to reproduce the laggy maps problem nor the kicked for flying problem either but blocks glitching out is reproducable today.
