### ISSUE TITLE
Borderless Mining conflict

### ISSUE THREAD

**Issue by creeper123123321** [ViaVersion/ViaFabric#62]
"ViaFabric and Borderless Mining seem to have a weird conflict when in fullscreen mode.  When the two mods are in place the screen flashes then gets offset like ViaFabric is trying to center the window while loading.  This results in not being able to click on buttons once loaded as borderless mining has now made the normal fullscreen "Windowed" borderless instead.  multiconnect does not have this issue nor does any other mods that I have setup.  The weird offset only happens when ViaFabric is enabled and loading.  

 

Mods: Borderless Mining 1.0.6 and ViaFabric 0.2.13 Build 477.1

I can give the full mods list if needed.  The big mod that affects rendering is OptiFabric/OptiFine."
https://www.curseforge.com/minecraft/mc-mods/viafabric#c17

**Comment by creeper123123321** [comment]
is it related with #101?

**Comment by Kichura** [comment]
Also not reproducable, also optifabric in general is known for being garbage.
