### ISSUE TITLE
Indicate broadcasted and actual version

### ISSUE THREAD

**Issue by Madis0** [ViaVersion/ViaFabric#69]
**Is your feature request related to a problem? Please describe.**
A clear way for the user to see what version of Minecraft or emulated version of ViaFabric they need to join a server.

**Is this related specifically to ViaFabric?**
(Optional)
- [ ] It seems to not apply for ViaVersion/ViaBackwards/ViaRewind installed on Bukkit/BungeeCord/Sponge/Velocity servers.

**Describe the solution you'd like**
Display the latest broadcasted version of a server below its player count in server list, on hover show the true version (based on actual protocol) too. See also: https://github.com/Earthcomputer/multiconnect/issues/24

**Describe alternatives you've considered**
Show both on hover.

**Which versions is this for?**
All

**Comment by Kichura** [comment]
Done, Can now be seen by hovering the ping icon whenever a specific server is added.
