### ISSUE TITLE
steal sword blocking resource pack from clientviaversion

### ISSUE THREAD

**Issue by creeper123123321** [ViaVersion/ViaFabric#71]
**Is your feature request related to a problem? Please describe.**

**Is this related specifically to ViaFabric?**
(Optional)
- [x] It seems to not apply for ViaVersion/ViaBackwards/ViaRewind installed on Bukkit/BungeeCord/Sponge/Velocity servers.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Which versions is this for?**
Does the feature apply to any specific versions? If so put them here.

**Comment by FlorianMichael** [comment]
ViaFabric 1.20.5+ versions now have proper sword blocking integrated in VV: https://github.com/ViaVersion/ViaVersion/pull/4010
