### ISSUE TITLE
Powder Snow Translation Fail

### ISSUE THREAD

**Issue by RealRTTV** [ViaVersion/ViaFabric#77]
**Describe the bug, provide any errors**
When placing Powder Snow on a 20w46a Client a 1.16.3 Client does not see the block or know its there or anything about it except for its slight screen zoom in and damage over time

**Is this happening specifically on ViaFabric?**
Yes

**How can we reproduce it?**
1. Start Up a 1.16.3 Fabric Client running ViaFabric and ViaVersion
2. Start Up a 20w46a Client
3.  Make a LAN World running on the 20w46a client
4. Place a 

**Expected behaviour**
The 1.16.3 Client will not see the powder snow and if a block is placed there the server will deny it

**Screenshots**
![2020-11-11_15 21 19](https://user-images.githubusercontent.com/72476111/98860445-af6bb100-2431-11eb-9f7d-8e2087fbfdbc.png)
![2020-11-11_15 21 15](https://user-images.githubusercontent.com/72476111/98860450-b09cde00-2431-11eb-9c3f-55be2e8c1ae5.png)

**ViaVersion Dump:**
No command because server running vanilla

**Additional server info**
Is server using a proxy (eg. BungeeCord/Waterfall/Travertine/Velocity)? What software is it using and what plugins? Are you running on client-side mode? (Debug hud (F3) has server brand)

I was but them all disabled except ViaFabric and ViaVersion after the first test
Oh and heres the jar to test it
[ViaVersion-3.3.0-20w46a.jar.txt](https://github.com/ViaVersion/ViaFabric/files/5526560/ViaVersion-3.3.0-20w46a.jar.txt)

**Comment by KennyTV** [comment]
ViaBackwards has not been updated yet for the new snapshot.
