### ISSUE TITLE
Keep Getting False Banned on 1.8 PVP Servers

### ISSUE THREAD

**Issue by YEEETT** [ViaVersion/ViaFabric#86]
**Describe the bug, provide any errors**
I have been banned on minemen.cub and pvp.land while using this mod.

**Is this happening specifically on ViaFabric?**
yes
- [ ] It seems to not happen when using ViaVersion/ViaBackwards/ViaRewind installed on Bukkit/BungeeCord/Sponge/Velocity server.

**How can we reproduce it?**
1. Login on 1.16.x
2. log into a 1.8 pvp server that does NOT have viaversion

**Expected behaviour**
not getting banned

**Screenshots**

**ViaVersion Dump:**
https://dump.viaversion.com/10cdf8067e0b72c4c0df005213f02b35db5eadd7c591777469c0f4cb6ba3f7a5

**Additional server info**
I did not check, probably bungeecoord or some fork of that

**Comment by astei** [comment]
You didn't read [the warning](https://github.com/ViaVersion/ViaFabric#warning) attached to this mod that states:

> I cannot guarantee that this mod is allowed on every (or even any) server. This mod may cause problems with anti cheat plugins. USE AT OWN RISK

You clearly disregarded this warning and shot yourself in the foot. Too bad.

**Comment by YEEETT** [comment]
ok
