### ISSUE TITLE
port to legacy fabric 1.7.10

### ISSUE THREAD

**Issue by creeper123123321** [ViaVersion/ViaFabric#87]
**Is your feature request related to a problem? Please describe.**

**Is this related specifically to ViaFabric?**
(Optional)
- [ ] It seems to not apply for ViaVersion/ViaBackwards/ViaRewind installed on Bukkit/BungeeCord/Sponge/Velocity servers.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Which versions is this for?**
Does the feature apply to any specific versions? If so put them here.

**Comment by HowardZHY** [comment]
A better choice for this is a liteloader mod

**Comment by creeper123123321** [comment]
moved to #85
