### ISSUE TITLE
Can't open inventory for 1.14 player!

### ISSUE THREAD

**Issue by Shyrogan** [ViaVersion/ViaFabric#88]
**Describe the bug, provide any errors**
When opening  some inventories in lower version than 1.16, we sometimes get an error:
`[16:31:48] [Netty Client IO #0/WARN] (ViaVersion) Can't open inventory for 1.14 player! Type: Chest Size: 54`

**Is this happening specifically on ViaFabric?**
I think this is due to ViaVersion but not entirely sure.

**How can we reproduce it?**
Use ViaFabric for 1.16, enable client-side version and use 1.9,  join `funcraft.net`, try to open a menu by right-clicking any item.

**Expected behaviour**
It should still open the inventory, I guess.

**Comment by creeper123123321** [comment]
Should be in ViaVersion
