### ISSUE TITLE
ViaFabric results in a ban within 2 skywars games on Hypixel

### ISSUE THREAD

**Issue by mpfaff** [ViaVersion/ViaFabric#98]
**Describe the bug, provide any errors**
When I remove Hypixel from the blacklisted servers and set ViaFabric to 1.8, my account will be banned within 2 skywars games.

**Is this happening specifically on ViaFabric?**
Yes.

**How can we reproduce it?**
1. Remove `"hypixel.net"` and `"*.hypixel.net"` from `client-side-force-disable` in `viafabric.yml`.
2. Enable ViaFabric client-side
3. Set version to `1.8.x`
4. Join Hypixel (use an alt)
5. Play skywars games until banned

**Expected behaviour**
ViaFabric allows playing on Hypixel without quickly resulting in a Watchdog cheating ban. I understand that Hypixel is blacklisted in the config by default, but at the very least an explanation should be provided to the user explaining the risks.

**Screenshots**

**ViaVersion Dump:**
If a dump is required I would be happy to provide one.

**Additional server info**
Client-side mode. Unknown server software.

**Comment by Camotoy** [comment]
The beginning of the config file reads:
```
# WARNING
# I cannot guarantee that this mod is allowed on every (or even any) server. This mod may cause problems with anti cheat plugins. USE AT OWN RISK
```

**Comment by mpfaff** [comment]
Oh. My config file had that half way through above the `enable-client-side` option, while `client-side-force-disable` was at the top. Generating a new config does put that at the top now. I think that's suitable for a warning.

Do you have any idea what is causing it to ban on Hypixel?

**Comment by Camotoy** [comment]
I'm not a ViaFabric developer, but I develop for a program that allows Bedrock players to connect to Java servers and we run into the same issue.
Hypixel's anticheat is most certainly the strictest out there - it even has checks down to the version you're playing on. So, Hypixel detects non-1.8 movement or behavior in a "1.8" client, and flags that.

**Comment by mpfaff** [comment]
That makes a lot of sense. I might look into developing a mod to mimic 1.8 movement (and any other mechanics that would be necessary), but I'd imagine it would be quite a lot of work.

**Comment by creeper123123321** [comment]
> That makes a lot of sense. I might look into developing a mod to mimic 1.8 movement (and any other mechanics that would be necessary), but I'd imagine it would be quite a lot of work.

When multiconnect support 1.8 it may do it

**Comment by Earthcomputer** [comment]
Bear in mind that multiconnect does not activate on hypixel for fear of its anti-cheat.
